### ISSUE TITLE
ValueError: Config entry has already been setup!

### ISSUE THREAD

**Issue by vlebourl** [iMicknl/ha-tahoma#16]
Some entries are added several time. For instance, covers:
```
2020-06-04 21:17:42 INFO (MainThread) [homeassistant.components.cover] Setting up cover.tahoma
2020-06-04 21:17:42 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry vlebourl@gmail.com for cover
Traceback (most recent call last):
  File "/home/vlb/.local/lib/python3.8/site-packages/homeassistant/config_entries.py", line 216, in async_setup
    result = await component.async_setup_entry(  # type: ignore
  File "/home/vlb/.local/lib/python3.8/site-packages/homeassistant/components/cover/__init__.py", line 159, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/home/vlb/.local/lib/python3.8/site-packages/homeassistant/helpers/entity_component.py", line 159, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2020-06-04 21:17:42 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry vlebourl@gmail.com for cover
Traceback (most recent call last):
  File "/home/vlb/.local/lib/python3.8/site-packages/homeassistant/config_entries.py", line 216, in async_setup
    result = await component.async_setup_entry(  # type: ignore
  File "/home/vlb/.local/lib/python3.8/site-packages/homeassistant/components/cover/__init__.py", line 159, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/home/vlb/.local/lib/python3.8/site-packages/homeassistant/helpers/entity_component.py", line 159, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2020-06-04 21:17:42 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry vlebourl@gmail.com for cover
Traceback (most recent call last):
  File "/home/vlb/.local/lib/python3.8/site-packages/homeassistant/config_entries.py", line 216, in async_setup
    result = await component.async_setup_entry(  # type: ignore
  File "/home/vlb/.local/lib/python3.8/site-packages/homeassistant/components/cover/__init__.py", line 159, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/home/vlb/.local/lib/python3.8/site-packages/homeassistant/helpers/entity_component.py", line 159, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
```

**Comment by iMicknl** [comment]
I can reproduce, not sure where too look for this issue. Open for suggestions.

**Comment by tetienne** [comment]
Here how I solved this issue for my component: https://github.com/home-assistant/core/blob/a012c617621a076c5fded1570625ca79d447bbe0/homeassistant/components/somfy/config_flow.py#L46

**Comment by iMicknl** [comment]
I tried adding the following snippet, but that didn't work. This also makes sure that you can only add the full integration once, where I think it could be nice for some users to be able to add multiple integrations.

```python
  if self.hass.config_entries.async_entries(DOMAIN):
            return self.async_abort(reason='already_setup')
```
