### ISSUE TITLE
cover/set_cover_position fails

### ISSUE THREAD

**Issue by vlebourl** [iMicknl/ha-tahoma#173]
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 125, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1250, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1285, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 454, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 595, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 485, in _handle_entity_call
    await result
  File "/config/custom_components/tahoma/cover.py", line 141, in async_set_cover_position
    await self.async_execute_command(command, position)
  File "/config/custom_components/tahoma/tahoma_device.py", line 176, in async_execute_command
    exec_id = await self.client.execute_command(
  File "/usr/local/lib/python3.8/site-packages/tahoma_api/client.py", line 144, in execute_command
    return await self.execute_commands(device_url, [command], label)
  File "/usr/local/lib/python3.8/site-packages/tahoma_api/client.py", line 157, in execute_commands
    response = await self.__post("exec/apply", payload)
  File "/usr/local/lib/python3.8/site-packages/tahoma_api/client.py", line 180, in __post
    async with self.session.post(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 365, in _request
    data = payload.JsonPayload(json, dumps=self._json_serialize)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/payload.py", line 389, in __init__
    dumps(value).encode(encoding),
  File "/usr/local/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type CommandDefinition is not JSON serializable
```

**Comment by tetienne** [comment]
'''

command = self.select_command(
            COMMAND_SET_POSITION, COMMAND_SET_CLOSURE, COMMAND_SET_PEDESTRIAN_POSITION
        )
        await self.async_execute_command(command, position)
'''

We have to update async_execute_command or pass command.command_name.
