### ISSUE TITLE
Tahoma installation fails login error

### ISSUE THREAD

**Issue by Glenn1986** [iMicknl/ha-tahoma#174]
Hi guys since a couple of days my tahoma integration didn't work anymore. I tried to delete the integreation and reinstall it. But now i have troubles to login. Gives an error while my pass and username are correct.

2020-07-25 16:46:10 ERROR (MainThread) [custom_components.tahoma.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/tahoma/config_flow.py", line 60, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/tahoma/config_flow.py", line 29, in validate_input
    await hass.async_add_executor_job(TahomaApi, username, password)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tahoma/tahoma_api.py", line 40, in __init__
    self.login()
  File "/config/custom_components/tahoma/tahoma_api.py", line 122, in login
    raise Exception("Could not login: " + result["error"])
Exception: Could not login: Bad credentials

**Comment by iMicknl** [comment]
Are you sure those credentials work on the TaHomalink.com website? Could you try the latest master? However, it should not make a huge difference.

**Comment by Glenn1986** [comment]
Strange. When I login on somfy.be there is no problem. When I'm logging in on the tahomalink.com website he gives also the bad login error. I tried to pasword forget procedure but didn't help. So the problem is somfy and not the integration.
