### ISSUE TITLE
object of type 'States' has no len()

### ISSUE THREAD

**Issue by iMicknl** [iMicknl/ha-tahoma#175]
**Describe the bug**
```
2020-07-26 16:00:29 ERROR (MainThread) [homeassistant.components.cover] Error while setting up tahoma platform for cover
Traceback (most recent call last):
  File "/Users/mick/Projects/personal-projects/home-assistant-core/homeassistant/helpers/entity_platform.py", line 188, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/Users/mick/Projects/personal-projects/home-assistant-core/homeassistant/helpers/entity_platform.py", line 294, in async_add_entities
    await asyncio.gather(*tasks)
  File "/Users/mick/Projects/personal-projects/home-assistant-core/homeassistant/helpers/entity_platform.py", line 453, in _async_add_entity
    entity.async_write_ha_state()
  File "/Users/mick/Projects/personal-projects/home-assistant-core/homeassistant/helpers/entity.py", line 287, in async_write_ha_state
    self._async_write_ha_state()
  File "/Users/mick/Projects/personal-projects/home-assistant-core/homeassistant/helpers/entity.py", line 334, in _async_write_ha_state
    assumed_state = self.assumed_state
  File "/Users/mick/.homeassistant/custom_components/tahoma/tahoma_device.py", line 69, in assumed_state
    return self.device.states is not None and len(self.device.states) > 0
TypeError: object of type 'States' has no len()
2020-07-26 16:00:29 ERROR (MainThread) [homeassistant.components.light] Error while setting up tahoma platform for light
Traceback (most recent call last):
  File "/Users/mick/Projects/personal-projects/home-assistant-core/homeassistant/helpers/entity_platform.py", line 188, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/Users/mick/Projects/personal-projects/home-assistant-core/homeassistant/helpers/entity_platform.py", line 294, in async_add_entities
    await asyncio.gather(*tasks)
  File "/Users/mick/Projects/personal-projects/home-assistant-core/homeassistant/helpers/entity_platform.py", line 453, in _async_add_entity
    entity.async_write_ha_state()
  File "/Users/mick/Projects/personal-projects/home-assistant-core/homeassistant/helpers/entity.py", line 287, in async_write_ha_state
    self._async_write_ha_state()
  File "/Users/mick/Projects/personal-projects/home-assistant-core/homeassistant/helpers/entity.py", line 334, in _async_write_ha_state
    assumed_state = self.assumed_state
  File "/Users/mick/.homeassistant/custom_components/tahoma/tahoma_device.py", line 69, in assumed_state
    return self.device.states is not None and len(self.device.states) > 0
TypeError: object of type 'States' has no len()
```

**return self.device.states is not None and len(self.device.states) > 0
TypeError: object of type 'States' has no len()**

**Additional context**
Behaviour using latest master, due to https://github.com/iMicknl/python-tahoma-api/pull/17.

**Comment by tetienne** [comment]
@iMicknl I will add this missing method to our API client. And probably some unit tests. 
Do you know if the states object returned by Somfy can exist and be empty?

**Comment by iMicknl** [comment]
@tetienne not sure, I don't have any devices without states. I just added the len() to be 100% sure.

@vlebourl do you know? I think you own devices without state.

**Comment by vlebourl** [comment]
I believe it can fit rts devices for instance.

**Comment by iMicknl** [comment]
@vlebourl but is states empty or is it non existing in the API response?

**Comment by pvroosendaal** [comment]
I'm experiencing the same issue. If I can help in any way, please let me know.

**Comment by iMicknl** [comment]
@pvroosendaal are you using the latest master? If you use 1.6.4 (https://github.com/iMicknl/ha-tahoma/releases/tag/v1.6.4), you should not face any problems.

Currently master is broken, but we will fix it tomorrow. We just switched to our new async Python library, but we need to make sure we pin the version and don't introduce breaking changes via our other repository.

**Comment by pvroosendaal** [comment]
@iMicknl I'm using master indeed. I'll try 1.6.4 now.

**Comment by pvroosendaal** [comment]
@iMicknl Updated to 1.6.4, works like a charm! Thanks a million!

**Comment by tetienne** [comment]
@vlebourl Can you please share your /setup that contains some RTS devices?
