### ISSUE TITLE
TypeError: __init__() missing 1 required keyword-only argument: 'ui_class'

### ISSUE THREAD

**Issue by jensihnow** [iMicknl/ha-tahoma#205]
**Describe the bug**

Integration stopped working after upgrade. Deleting the config and re-creating doesn't help. I also deleted the entire tahoma folder under custom_components and put the files back into it, no improvement.

**To Reproduce**

1. Upgrade to latest 2.0.0
2. Restart HA
3. See all entities offline and exception
4. Deleted integration
5. Restarted
6. Configured it again
7. Same exception, no devices discovered

**Expected behavior**
...

**Screenshots**

**Environment (please complete the following information):**

**ha-tahoma version:**  2.0.0
**Home Assistant version:** 0.113.3
**Platform**: All

**Additional context**

> 2020-08-05 22:00:20 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 123@456.78 for tahoma
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 219, in async_setup
>     result = await component.async_setup_entry(  # type: ignore
>   File "/config/custom_components/tahoma/__init__.py", line 92, in async_setup_entry
>     devices=await client.get_devices(),
>   File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 82, in get_devices
>     devices = [Device(**d) for d in humps.decamelize(response)]
>   File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 82, in <listcomp>
>     devices = [Device(**d) for d in humps.decamelize(response)]
> TypeError: __init__() missing 1 required keyword-only argument: 'ui_class'

**Comment by tetienne** [comment]
Apparently some of your devices haven't any ui class.

Can you please follow these steps: https://github.com/totalimmersion/com.somfy.tahoma/files/2755935/Instructions.for.the.TaHoma.devices.pdf

**Comment by jensihnow** [comment]
Well, it shouldn't fail like this anyways. I believe assuming we have had any device ever created made available might lead to issues.

My first guess is a match the left overs from the ZWAVE integration might be the devies with mising uiClass, see:


```json
    {
      "creationTime": 1472213846000,
      "lastUpdateTime": 1472213846000,
      "label": "ZWAVE (2#1)",
      "deviceURL": "zwave://xxxx-xxxx-xxxx/2#1",
      "shortcut": false,
      "controllableName": "zwave:ZWaveOccupancySensor",
      "definition": {
        "commands": [],
        "states": [],
        "dataProperties": [],
        "qualifiedName": "zwave:ZWaveOccupancySensor",
        "type": "UNKNOWN"
      },
      "available": false,
      "enabled": true,
      "placeOID": "xxx",
      "type": 0,
      "oid": "xxx-xxx-xxx-xxx-xxx"
    },
    {
      "creationTime": 1472213846000,
      "lastUpdateTime": 1472213846000,
      "label": "ZWAVE (2#2)",
      "deviceURL": "zwave://xxxx-xxxx-xxxx/2#2",
      "shortcut": false,
      "controllableName": "zwave:ZWaveTemperatureSensor",
      "definition": {
        "commands": [
          {
            "commandName": "refreshTemperature",
            "nparams": 0
          }
        ],
        "states": [
          {
            "values": [
              "failed"
            ],
            "type": "DiscreteState",
            "qualifiedName": "core:DeviceDefectState"
          },
          {
            "type": "DataState",
            "qualifiedName": "core:NeighboursAddressesState"
          },
          {
            "type": "ContinuousState",
            "qualifiedName": "core:TemperatureState"
          }
        ],
        "dataProperties": [],
        "widgetName": "TemperatureSensor",
        "uiClass": "TemperatureSensor",
        "qualifiedName": "zwave:ZWaveTemperatureSensor",
        "type": "SENSOR"
      },
      "attributes": [
        {
          "name": "core:MeasuredValueType",
          "type": 3,
          "value": "core:TemperatureInCelcius"
        }
      ],
      "available": false,
      "enabled": true,
      "placeOID": "xxx",
      "widget": "TemperatureSensor",
      "type": 2,
      "oid": "xxx-xxx-xxx-xxx-xxx",
      "uiClass": "TemperatureSensor"
    },
    {
      "creationTime": 1472213846000,
      "lastUpdateTime": 1472213846000,
      "label": "ZWAVE (2#3)",
      "deviceURL": "zwave://xxxx-xxxx-xxxx/2#3",
      "shortcut": false,
      "controllableName": "zwave:ZWaveLightSensor",
      "definition": {
        "commands": [],
        "states": [
          {
            "values": [
              "failed"
            ],
            "type": "DiscreteState",
            "qualifiedName": "core:DeviceDefectState"
          },
          {
            "type": "ContinuousState",
            "qualifiedName": "core:LuminanceState"
          },
          {
            "type": "DataState",
            "qualifiedName": "core:NeighboursAddressesState"
          }
        ],
        "dataProperties": [],
        "widgetName": "LuminanceSensor",
        "uiClass": "LightSensor",
        "qualifiedName": "zwave:ZWaveLightSensor",
        "type": "SENSOR"
      },
      "attributes": [
        {
          "name": "core:MeasuredValueType",
          "type": 3,
          "value": "core:LuminanceInLux"
        }
      ],
      "available": false,
      "enabled": true,
      "placeOID": "xxx",
      "widget": "LuminanceSensor",
      "type": 2,
      "oid": "xxx-xxx-xxx-xxx-xxx",
      "uiClass": "LightSensor"
    }
```

Interestingly, I did deleted the Z-Wave devices from TaHoma, still the API gives the items. Might be another Somfy Bug, but the intrgration should ignore them.

**Comment by iMicknl** [comment]
Thanks for reporting, @jensihnow.

Indeed, we need to make `ui_class` optional in https://github.com/iMicknl/python-tahoma-api and ignore it in the HA integration.

**Comment by jensihnow** [comment]
I did already, thanks for taking care of it.

**Comment by tetienne** [comment]
@jensihnow Your issue must be fixed now with the 2.0.1.

**Comment by jensihnow** [comment]
Just tried 2.01, not working for me. Now I'm getting this one, which might be a follow-up on the previous issue just this time it is _widgetName_.

```
2020-08-11 16:25:30 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxx@xxx.xx for tahoma
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 219, in async_setup
    result = await component.async_setup_entry(  # type: ignore
  File "/config/custom_components/tahoma/__init__.py", line 92, in async_setup_entry
    devices=await client.get_devices(),
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 82, in get_devices
    devices = [Device(**d) for d in humps.decamelize(response)]
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 82, in <listcomp>
    devices = [Device(**d) for d in humps.decamelize(response)]
  File "/usr/local/lib/python3.8/site-packages/pyhoma/models.py", line 52, in __init__
    self.definition = Definition(**definition)
TypeError: __init__() missing 1 required keyword-only argument: 'widget_name'
```

**Comment by iMicknl** [comment]
@jensihnow thanks for reporting, we will work on another bugfix. Hopefully this will finally resolve it ;-).

**Comment by jensihnow** [comment]
Unfortunately I need to report another issue while testing with 2.1.0:

```
2020-08-20 18:32:49 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxx@xxx.xx for tahoma
ValueError: 0 is not a valid ProductType
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 222, in async_setup
    result = await component.async_setup_entry(  # type: ignore
  File "/config/custom_components/tahoma/__init__.py", line 92, in async_setup_entry
    devices=await client.get_devices(),
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 82, in get_devices
    devices = [Device(**d) for d in humps.decamelize(response)]
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 82, in <listcomp>
    devices = [Device(**d) for d in humps.decamelize(response)]
  File "/usr/local/lib/python3.8/site-packages/pyhoma/models.py", line 62, in __init__
    self.type = ProductType(type)
  File "/usr/local/lib/python3.8/enum.py", line 304, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 595, in __new__
    raise exc
  File "/usr/local/lib/python3.8/enum.py", line 579, in __new__
    result = cls._missing_(value)
  File "/usr/local/lib/python3.8/enum.py", line 608, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 0 is not a valid ProductType
```

**Comment by iMicknl** [comment]
@jensihnow it should (finally) be fixed now in the latest master. However, would be great if you could give #227 a try!

**Comment by jensihnow** [comment]
Works like a charm now. I updated to the branch code and restartet, worked already. Since I had the Z-Wave devices still listed I did removed and added the integration again. But I found something else I'm going to add issues for.
