### ISSUE TITLE
Attempt to decode JSON with unexpected mimetype

### ISSUE THREAD

**Issue by halest** [iMicknl/ha-tahoma#228]
**Describe the bug**
cover.set_cover_position throws an error. Calling said function through lovelace, the entity or developer tools throws and toasts below attached exception. It had worked until this morning, no other changes happened on the system.

**To Reproduce**
Call cover.set_cover_position

**Environment (please complete the following information):**

- **ha-tahoma version:** 2.0.1
- **Home Assistant version:** 0.113.3
- **Platform**: cover

> 2020-08-14 18:35:16 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1775640952] 0, message='Attempt to decode JSON with unexpected mimetype: ', url='https://tahomalink.com/enduser-mobile-web/enduserAPI/exec/apply
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 125, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1281, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1316, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 454, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 595, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 485, in _handle_entity_call
    await result
  File "/config/custom_components/tahoma/cover.py", line 219, in async_stop_cover
    await self.async_execute_command(
  File "/config/custom_components/tahoma/tahoma_device.py", line 155, in async_execute_command
    await self.coordinator.client.execute_command(
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 157, in execute_command
    return await self.execute_commands(device_url, [command], label)
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 170, in execute_commands
    response = await self.__post("exec/apply", payload)
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 196, in __post
    await self.check_response(response)
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 209, in check_response
    result = await response.json()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1026, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url='https://tahomalink.com/enduser-mobile-web/enduserAPI/exec/apply

**Comment by iMicknl** [comment]
Thanks for reporting, @halest. This is possibly related to https://github.com/iMicknl/python-tahoma-api/issues/35.

For now, restarting Home Assistant should work, but we will have a look for a better solution. :-)

**Comment by halest** [comment]
Hello iMicknl, sorry, I somehow didn't see that scanning the issues. I wanted to document the error before restarting (I was just about to update to 0.114).
Feel free to mark this as duplicate and thanks for the answer! Also, have a nice weekend

**Comment by iMicknl** [comment]
@halest the other issue is in the client repository, so good to keep this one open here as well for tracking purposes. 👍🏻
