### ISSUE TITLE
Error unloading entry ... for tahoma

### ISSUE THREAD

**Issue by jensihnow** [iMicknl/ha-tahoma#239]
**Describe the bug**

When deleting the integration it is throwing errors for, as it seems like, a lot of items:

```
2020-08-27 20:37:01 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry ...email... for tahoma
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 309, in async_unload
    result = await component.async_unload_entry(  # type: ignore
  File "/config/custom_components/tahoma/__init__.py", line 156, in async_unload_entry
    await hass.data[DOMAIN][entry.entry_id].get("update_listener")()
TypeError: object NoneType can't be used in 'await' expression
2020-08-27 20:37:01 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/alexa/state_report.py", line 184, in async_send_delete_message
    alexa_entity = ENTITY_ADAPTERS[domain](hass, config, hass.states.get(entity_id))
  File "/usr/src/homeassistant/homeassistant/components/alexa/entities.py", line 211, in __init__
    self.entity_conf = config.entity_config.get(entity.entity_id, {})
AttributeError: 'NoneType' object has no attribute 'entity_id'
2020-08-27 20:37:01 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/alexa/state_report.py", line 184, in async_send_delete_message
    alexa_entity = ENTITY_ADAPTERS[domain](hass, config, hass.states.get(entity_id))
  File "/usr/src/homeassistant/homeassistant/components/alexa/entities.py", line 211, in __init__
    self.entity_conf = config.entity_config.get(entity.entity_id, {})
AttributeError: 'NoneType' object has no attribute 'entity_id'
... shortened the output...
```

**To Reproduce**

1. Delete the integration while having Alexa integration active.

**Expected behavior**

No such exceptions on deletion of integration.

**Screenshots**
-

**Environment (please complete the following information):**

- **ha-tahoma version:** branch #227
- **Home Assistant version:** 0.114.4
- **Platform**: -

**Device:** -
- **Model**: -
- **Type**: -

**Additional context**

-

**Comment by iMicknl** [comment]
@jensihnow it should be fixed now in #227. 👍🏻 Thanks for reporting!
