### ISSUE TITLE
Handle ServerDisconnectedError during startup

### ISSUE THREAD

**Issue by laszlojakab** [iMicknl/ha-tahoma#277]
- [x] **I have read the [Readme](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [Advanced](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section regarding debugging.**

**Is your feature request related to a problem? Please describe.**
I often restart HA for development purposes. A lot of times I get ServerDisconnectedError from tahoma integration during startup. All my covers are unavailable and I never get them back until I restart HA again (and not getting ServerDisconnectedError again). 

Stacktrace:

```
2020-09-28 21:54:37 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry *****@*****.com for tahoma
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 228, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/tahoma/__init__.py", line 108, in async_setup_entry
    devices=await client.get_devices(),
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 98, in get_devices
    response = await self.__get("setup/devices")
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 239, in __get
    async with self.session.get(f"{self.api_url}{endpoint}") as response:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError
```

**Describe the solution you'd like**
It would be great to store previously discovered devices, and register them in HA in "unavailable" state during startup if server is unavailable. When connection is restored than just change the actual state of devices.

**Comment by iMicknl** [comment]
Thanks for reporting. Do you have (public) internet access when you restart Home Assistant?

We should definitely retry on `ServerDisconnectedError` in https://github.com/iMicknl/python-tahoma-api. I am not sure if we can easily schedule a task that will check if there is internet connectivity again.. However, you don't need to restart HA, you could also press the reload button on the integrations page.

<img width="358" alt="Screenshot 2020-09-28 at 23 08 42" src="https://user-images.githubusercontent.com/1424596/94486342-91c6ed00-01df-11eb-8db9-77e21166cc0a.png">

**Comment by laszlojakab** [comment]
Hi @iMicknl , Yes, I have internet access during restart (only HA restarted, host system stays online). Thanks for "reload button idea" I will check next time!

**Comment by laszlojakab** [comment]
Hi @iMicknl, I checked "reload button" workaround for the problem. As I see the reload function is not available if the integration fails during startup.

On the first screenshot ServerDisconnectedError happened during init:

![image](https://user-images.githubusercontent.com/6196882/94609653-6277b500-029f-11eb-9e51-1efd4b958d71.png)

On the second screenshot the same menu, when no error occured:

![image](https://user-images.githubusercontent.com/6196882/94609730-7b806600-029f-11eb-8d08-8f90b11ed4e1.png)

**Comment by iMicknl** [comment]
Good catch. Can you give this version a try: https://github.com/iMicknl/ha-tahoma/archive/enhancement/better_handle_errors.zip. You can install it manually by unzipping the package and placing `custom_components/tahoma` in your custom_components folder.

**Comment by laszlojakab** [comment]
With better_handle_errors.zip version:

```2020-10-01 10:53:51 DEBUG (MainThread) [custom_components.tahoma] Finished fetching TaHoma Event Fetcher data in 5.375 seconds
2020-10-01 10:53:51 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry ******@******.com for tahoma
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 228, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/tahoma/__init__.py", line 122, in async_setup_entry
    entities[SCENE] = await client.get_scenarios()
  File "/usr/local/lib/python3.8/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 239, in get_scenarios
    response = await self.__get("actionGroups")
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 252, in __get
    async with self.session.get(f"{self.api_url}{endpoint}") as response:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError```

**Comment by iMicknl** [comment]
That is weird, this happens at the retrieval of the scenes... That means that the ServerDisconnectedError occurs just after we did the login and retrieval of the entities.

I haven't faced this ServerDisconnectedError that much, only during polling at a low frequency..

**Comment by iMicknl** [comment]
Can you give https://github.com/iMicknl/ha-tahoma/archive/enhancement/better_handle_errors.zip a try again. I did add all API calls to the try/catch mechanisme.

However, there is no retry logic yet, that should be added to `python-tahoma-api`. Do you still face these issues?

**Comment by laszlojakab** [comment]
I have less problems in the last week. I haven't tried the zipped version yet. Is v2.3.4 contains the same error handling logic as the zip?

**Comment by iMicknl** [comment]
> I have less problems in the last week. I haven't tried the zipped version yet. Is v2.3.4 contains the same error handling logic as the zip?

Yes, since 2.3.2 better error handling is included.
