### ISSUE TITLE
Node Red API Scene Error

### ISSUE THREAD

**Issue by dckiller51** [iMicknl/ha-tahoma#297]
- [x] **I have read the [Readme](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [Advanced](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section regarding debugging.**

**Describe the bug**

Hello, I often have a scene problem for about 1 week. At 8:00 am mainly. Weird at 7:30 am ok, At sunset OK. I am using Node Red to start the scene. I have an API error. If I manually restart the Node, no problem.

**Expected behavior**
`Logger: homeassistant.components.websocket_api.http.connection.140316558856640
Source: custom_components/tahoma/scene.py:36
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 8:00:00 (2 occurrences)
Last logged: 8:00:00

Server busy, please try again later. (Too many executions)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 138, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1335, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1370, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 470, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 655, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 507, in _handle_entity_call
    await result
  File "/config/custom_components/tahoma/scene.py", line 36, in async_activate
    await self.client.execute_scenario(self.scenario.oid)
  File "/usr/local/lib/python3.8/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 247, in execute_scenario
    response = await self.__post(f"exec/{oid}")
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 263, in __post
    await self.check_response(response)
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 303, in check_response
    raise TooManyExecutionsException(message)
pyhoma.exceptions.TooManyExecutionsException: Server busy, please try again later. (Too many executions)`

**Environment (please complete the following information):**

- **ha-tahoma version:** V2.3.4
- **Home Assistant version:** 0.116.4
- **Platform**: Scene

**Comment by iMicknl** [comment]
The `TooManyExecutionsException` is due to Somfy only allowing 10 running executions at the same time. How many devices do you have and do you perhaps have any (long running) executions running at the time of the error.

We track this issue in #261, thus I will close this issue. A fix is not implemented yet.
