### ISSUE TITLE
Repeating error in logs

### ISSUE THREAD

**Issue by rvrignaud** [iMicknl/ha-tahoma#312]
- [ ] **I have read the [Readme](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [Advanced](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section regarding debugging.**

**Describe the bug**
I have installed Homeassistant 0.117.6
I install ha-tahoma with git commit 50f352b2b0e9024d6fa5128ea102c5f9406bb0e4
I setup the Google Assistant integration with nabucasa.

In HA I can see the RollerShutter I wanted to manage and properly control them (open & close shutter from Home Assistant).
However when used through Google Home I have following problem:
  - I can only move the shutter up.
  - I see offline state
  - I think Google Home is trying to refresh the state of the device
  - I have continuously this error in Home Assistant logs:

```
2020-11-12 16:26:52 ERROR (MainThread) [homeassistant.components.google_assistant.smart_home] Unexpected error serializing query for <state cover.salle_d_eau=unknown; ui_class=RollerShutter, widget=UpDownRollerShutter, controllable_name=profalux868:Profalux868RollerShutter, friendly_name=Salle d'eau, assumed_state=True, supported_features=11, device_class=shutter @ 2020-11-12T15:25:42.017197+00:00>
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/google_assistant/smart_home.py", line 141, in async_devices_query
    devices[devid] = entity.query_serialize()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/google_assistant/helpers.py", line 489, in query_serialize
    deep_update(attrs, trt.query_attributes())
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/google_assistant/trait.py", line 1565, in query_attributes
    raise SmartHomeError(
homeassistant.components.google_assistant.error.SmartHomeError: Querying state is not supported
```

**To Reproduce**

1. Setup Roller Shutter integration with Profalux 868 dongle in Tahoma
2. Deploy Home Assistant 0.117.6
3. Install ha-tahoma with commit 50f352b2b0e9024d6fa5128ea102c5f9406bb0e4
3. Setup Google Assistant integration
4. Try to Close the Shutter

**Expected behavior**
I would like to be able to open & close all the shutters in Google Home applicationn.
I know that 868 protocols doesn't allow to report shutter state

**Screenshots**
https://photos.app.goo.gl/gNW4KzkDGKpPwPGB6

**Environment (please complete the following information):**

- **ha-tahoma version:** commit 50f352b2b0e9024d6fa5128ea102c5f9406bb0e4
- **Home Assistant version:** 0.117.6
- **Platform**: RollerShutter

**Device:** 

- **Model**: UpDownRollerShutter by Somfy
- **Type**: Firmware: profalux868:Profalux868RollerShutter

**Comment by rvrignaud** [comment]
Btw I tried with manual setup for Google Home integration and I have the exact same behavior.
So this is not related to nabucasa integration

**Comment by iMicknl** [comment]
Thanks for reporting @rvrignaud. I see you also reported it via https://github.com/home-assistant/core/issues/43178. Let's see if any changes in `ha-tahoma` are required.

**Comment by rvrignaud** [comment]
Closing this one as the problem was in Google Assistant integration in core
