### ISSUE TITLE
[custom_components.tahoma] Too many requests, try again later.

### ISSUE THREAD

**Issue by jaddel** [iMicknl/ha-tahoma#409]
- [ ] **I have read the [Readme](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [Advanced](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section regarding debugging.**

**Describe the bug**

Somfy shades being unresponsive. 
My pooling intervall is set to 180sec.

The HA core log says:

```
2021-03-23 18:39:17 WARNING (MainThread) [homeassistant.loader] You are using a custom integration tahoma which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-03-23 18:39:17 WARNING (MainThread) [homeassistant.loader] You are using a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-03-23 18:39:17 WARNING (MainThread) [homeassistant.loader] You are using a custom integration adaptive_lighting which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-03-23 18:39:28 ERROR (MainThread) [custom_components.tahoma] Too many requests, try again later.
2021-03-23 18:39:28 WARNING (MainThread) [homeassistant.config_entries] Config entry 'max.uhsadel@gmail.com' for tahoma integration not ready yet. Retrying in background
2021-03-23 18:39:30 WARNING (MainThread) [homeassistant.components.threshold.binary_sensor] State is not numerical
2021-03-23 18:39:30 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 247, in _websocket_forward
await ws_to.send_bytes(msg.data)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_ws.py", line 307, in send_bytes
await self._writer.send(data, binary=True, compress=compress)
File "/usr/local/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 685, in send
await self._send_frame(message, WSMsgType.BINARY, compress)
File "/usr/local/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 650, in _send_frame
self._write(header + message)
File "/usr/local/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 660, in _write
raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
2021-03-23 18:39:30 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 129, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 54, in _handle
return await self._handle_websocket(request, token, path)
File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 86, in _handle_websocket
await ws_server.prepare(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_ws.py", line 135, in prepare
payload_writer = await super().prepare(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_response.py", line 378, in prepare
return await self._start(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_response.py", line 386, in _start
await self._write_headers()
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_response.py", line 458, in _write_headers
await writer.write_headers(status_line, self._headers)
File "/usr/local/lib/python3.8/site-packages/aiohttp/http_writer.py", line 119, in write_headers
self._write(buf)
File "/usr/local/lib/python3.8/site-packages/aiohttp/http_writer.py", line 67, in _write
raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
2021-03-23 18:39:34 ERROR (MainThread) [custom_components.tahoma] Too many requests, try again later.
2021-03-23 18:39:44 ERROR (MainThread) [custom_components.tahoma] Too many requests, try again later.
2021-03-23 18:40:04 ERROR (MainThread) [custom_components.tahoma] Too many requests, try again later.
```

**Environment (please complete the following information):**

- **Hub**: Somfy Connexoon
- **ha-tahoma version**: 2.4.8
- **Home Assistant version**: core-2021.3.4
- **Platform**: cover

- **Model**: Device info PositionableRollerShutterUno by Somfy Firmware: io:RollerShutterUnoIOComponent

**Comment by iMicknl** [comment]
Unfortunately this is not something we can control, since it is caused by the rate limiting by Somfy. With normal use, you should not face this error. Based on your log, it seems that you hit this error on Home Assistant start.

We face this error mainly during the development of this integration. @jaddel did you perhaps restart your Home Assistant many times in a row? (or do you use this integration on multiple installations).

**Comment by jaddel** [comment]
> Unfortunately this is not something we can control, since it is caused by the rate limiting by Somfy. With normal use, you should not face this error. Based on your log, it seems that you hit this error on Home Assistant start.
> 
> We face this error mainly during the development of this integration. @jaddel did you perhaps restart your Home Assistant many times in a row? (or do you use this integration on multiple installations).

thanks for your quick reply. No, i don't use it on multipel instances. Indeed i just restartet homeassitant because the shades weren't working. Any how I have this issue since i installed the integration around 4 weeks ago. In the beginning the pooling was set to 30sec because off the errors shown in the logs i set it to 180sec but it doesn't seem to make any difference.

**Comment by iMicknl** [comment]
When you face this error, best is to disable (or remove) the integration for some hours. Afterwards you can re enable the integration.

A polling of 30 seconds should be fine though, thus I am not sure why this is an issue. Normally it only happens when you restart a few times in a small timeframe.

**Comment by jaddel** [comment]
ok I'll try. Thank you!

**Comment by jaddel** [comment]
> When you face this error, best is to disable (or remove) the integration for some hours. Afterwards you can re enable the integration.
> 
> 
> 
> A polling of 30 seconds should be fine though, thus I am not sure why this is an issue. Normally it only happens when you restart a few times in a small timeframe.

I followed your suggestion and disabled the integration over night. Since then I hade no errors. 

Thank you.
