### ISSUE TITLE
Disarm alarm activate private life option on somfy outdoor camera

### ISSUE THREAD

**Issue by PoVPoV29** [iMicknl/ha-tahoma#434]
Hello,
When I launch the following service  : 
`service: alarm_control_panel.alarm_disarm
target:
  entity_id: alarm_control_panel.cuisine`

("cusine" is my Somfy one device)

the "virtual" shutter of my Somfy outdoor camera is activate.
I don't know if it's a bug or a API issue on Somfy side.
Here the information for the virtual shutter on my Somfy outdoor camera : 
`core:CloudDeviceStatusState: online
friendly_name: Allée
supported_features: 3
device_class: shutter`

In my Somfy app, I have the option which allow me to keep the virtual shutter open when I disarm the alarm.
Maybe this option is applied only when the alarm is disarm through the app.

- Hub: Somfy TaHoma
- ha-tahoma version: 2.4.9
- Home Assistant version:  2021.4.6

**Comment by iMicknl** [comment]
Could you execute it via the Somfy app, and than open Home Assistant -> Services, run `tahoma.get_execution_history`. It will print the executed commands in your log.

If you can copy the specific command here, we can have a look if we can support it.

**Comment by PoVPoV29** [comment]
Hello,
I have the following logs when I execute your command : 
`2021-04-29 12:44:32 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'DAWN_TRIGGER' is not a valid ExecutionSubType
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 359, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 559, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 719, in admin_handler
    await result
  File "/config/custom_components/tahoma/__init__.py", line 252, in handle_get_execution_history
    await write_execution_history_to_log(tahoma_coordinator.client)
  File "/config/custom_components/tahoma/__init__.py", line 306, in write_execution_history_to_log
    history = await client.get_execution_history()
  File "/usr/local/lib/python3.8/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 152, in get_execution_history
    execution_history = [HistoryExecution(**h) for h in humps.decamelize(response)]
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 152, in <listcomp>
    execution_history = [HistoryExecution(**h) for h in humps.decamelize(response)]
  File "/usr/local/lib/python3.8/site-packages/pyhoma/models.py", line 484, in __init__
    self.execution_sub_type = ExecutionSubType(execution_sub_type)
  File "/usr/local/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 662, in __new__
    raise ve_exc
ValueError: 'DAWN_TRIGGER' is not a valid ExecutionSubType
2021-04-29 12:44:32 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281473283613216] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 18, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 439, in handle_execute_script
    await script_obj.async_run(context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1200, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 341, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 359, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 559, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 719, in admin_handler
    await result
  File "/config/custom_components/tahoma/__init__.py", line 252, in handle_get_execution_history
    await write_execution_history_to_log(tahoma_coordinator.client)
  File "/config/custom_components/tahoma/__init__.py", line 306, in write_execution_history_to_log
    history = await client.get_execution_history()
  File "/usr/local/lib/python3.8/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 152, in get_execution_history
    execution_history = [HistoryExecution(**h) for h in humps.decamelize(response)]
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 152, in <listcomp>
    execution_history = [HistoryExecution(**h) for h in humps.decamelize(response)]
  File "/usr/local/lib/python3.8/site-packages/pyhoma/models.py", line 484, in __init__
    self.execution_sub_type = ExecutionSubType(execution_sub_type)
  File "/usr/local/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 662, in __new__
    raise ve_exc
ValueError: 'DAWN_TRIGGER' is not a valid ExecutionSubType`

**Comment by vlebourl** [comment]
Hi, thanks for the report, can you edit your post and paste again using a code bloc? past your bloc and add 3 back quotes (```) before and after.

**Comment by PoVPoV29** [comment]
```2021-04-29 12:44:32 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'DAWN_TRIGGER' is not a valid ExecutionSubType
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 359, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 559, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 719, in admin_handler
    await result
  File "/config/custom_components/tahoma/__init__.py", line 252, in handle_get_execution_history
    await write_execution_history_to_log(tahoma_coordinator.client)
  File "/config/custom_components/tahoma/__init__.py", line 306, in write_execution_history_to_log
    history = await client.get_execution_history()
  File "/usr/local/lib/python3.8/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 152, in get_execution_history
    execution_history = [HistoryExecution(**h) for h in humps.decamelize(response)]
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 152, in <listcomp>
    execution_history = [HistoryExecution(**h) for h in humps.decamelize(response)]
  File "/usr/local/lib/python3.8/site-packages/pyhoma/models.py", line 484, in __init__
    self.execution_sub_type = ExecutionSubType(execution_sub_type)
  File "/usr/local/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 662, in __new__
    raise ve_exc
ValueError: 'DAWN_TRIGGER' is not a valid ExecutionSubType
2021-04-29 12:44:32 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281473283613216] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 18, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 439, in handle_execute_script
    await script_obj.async_run(context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1200, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 341, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 359, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 559, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 719, in admin_handler
    await result
  File "/config/custom_components/tahoma/__init__.py", line 252, in handle_get_execution_history
    await write_execution_history_to_log(tahoma_coordinator.client)
  File "/config/custom_components/tahoma/__init__.py", line 306, in write_execution_history_to_log
    history = await client.get_execution_history()
  File "/usr/local/lib/python3.8/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 152, in get_execution_history
    execution_history = [HistoryExecution(**h) for h in humps.decamelize(response)]
  File "/usr/local/lib/python3.8/site-packages/pyhoma/client.py", line 152, in <listcomp>
    execution_history = [HistoryExecution(**h) for h in humps.decamelize(response)]
  File "/usr/local/lib/python3.8/site-packages/pyhoma/models.py", line 484, in __init__
    self.execution_sub_type = ExecutionSubType(execution_sub_type)
  File "/usr/local/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 662, in __new__
    raise ve_exc
ValueError: 'DAWN_TRIGGER' is not a valid ExecutionSubType```

**Comment by iMicknl** [comment]
This requires a change in our underlying library... Unfortunately it doesn't show your commands currently.

**Comment by PoVPoV29** [comment]
How can you provide you the commands if the "tahoma.get_execution_history" is not working ?

**Comment by iMicknl** [comment]
@tetienne could you perhaps update pyhoma to https://github.com/iMicknl/python-tahoma-api/releases/tag/v0.5.13 if you have time some day? Otherwise, I will pick this up when I am back.

**Comment by PoVPoV29** [comment]
Hello,
I fixed the issue yesterday : the private life option is activate when the alarm is disactivated two time (through API or Somfy mobile app or token). But the private life option status is not retrieve actually. Is the v0.5.13 can correct that ?
When I try to install is through HACS, it tells me : Repostitory structure for v0.5.13 is not compliant

**Comment by iMicknl** [comment]
> But the private life option status is not retrieve actually. Is the v0.5.13 can correct that ?
> When I try to install is through HACS, it tells me : Repostitory structure for v0.5.13 is not compliant

5.0.13 of our underlying pyhoma library will only fix the `tahoma.get_execution_history` for you. It is now part of the latest master version of this integration, thus you could install that one to give it a try.

**Comment by PoVPoV29** [comment]
How can I install the 5.0.13 ?

**Comment by iMicknl** [comment]
> How can I install the 5.0.13 ?

You cannot just install our underlying library, but as mentioned above it is part of our 'master' branch. https://github.com/iMicknl/ha-tahoma/archive/refs/heads/master.zip? Extract this file and place `custom_components/tahoma` in your `custom_components` folder.

**Comment by PoVPoV29** [comment]
Hello,
The status of the virtual shutter (private life) is still in a unknow state after the update : 
![Outdoorcam](https://user-images.githubusercontent.com/69581008/120106513-7c82d380-c15d-11eb-8551-e9763dc9a18a.PNG)
