### ISSUE TITLE
 Unexpected error fetching device events data: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by rvrignaud** [iMicknl/ha-tahoma#465]
**Describe the bug**
I can see this error in the logs. Not sure if this is related to the fact that I'm hit by the "Too many request problem"  
```
Jul 07 10:47:26 pi hass[944]: 2021-07-07 10:47:26 ERROR (MainThread) [custom_components.tahoma] Unexpected error fetching device events data: argument of type 'NoneType' is not iterable in logs when running
Jul 07 10:47:26 pi hass[944]: Traceback (most recent call last):
Jul 07 10:47:26 pi hass[944]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
Jul 07 10:47:26 pi hass[944]:     self.data = await self._async_update_data()
Jul 07 10:47:26 pi hass[944]:   File "/home/homeassistant/.homeassistant/custom_components/tahoma/coordinator.py", line 118, in _async_update_data
Jul 07 10:47:26 pi hass[944]:     if state.name not in device.states:
Jul 07 10:47:26 pi hass[944]: TypeError: argument of type 'NoneType' is not iterable
Jul 07 10:47:26 pi hass[944]: 2021-07-07 10:47:26 INFO (MainThread) [custom_components.tahoma] Fetching device events data recovered
``` 
core-2021.6.6 and ha-tahoma v2.4.10

**To Reproduce**
This happened when asked to close 13 shutters through Google Assistant

**Expected behavior**
All shutter closing

**Screenshots**

**Environment (please complete the following information):**

- **Hub**: [Somfy TaHoma
- **ha-tahoma version:** [e.g. 2.0.0]
- **Home Assistant version:** core-2021.6.6
- **Platform**: cover

**Device:** 

- **Model**: [
- **Type**: UpDownRollerShutter
by Somfy
Firmware: profalux868:Profalux868RollerShutter

**Additional context**
```
2021-07-07 10:45:05 ERROR (MainThread) [custom_components.tahoma.tahoma_entity] Execution queue is full on gateway: #1227-3332-5186 (soft limit: 10)
```
and 
```
Jul 07 10:50:49 pi hass[944]: 2021-07-07 10:50:49 INFO (MainThread) [backoff] Backing off execute_commands(...) for 0.2s (pyhoma.exceptions.NotAuthenticatedException: Not authenticated)
Jul 07 10:50:49 pi hass[944]: 2021-07-07 10:50:49 ERROR (MainThread) [custom_components.tahoma.tahoma_entity] Too many requests, try again later : login with REDACTED@gmail.com
```
Not sure if this is related

**Comment by iMicknl** [comment]
@rvrignaud sorry for the late reply, do you still have this issue?

**Comment by rvrignaud** [comment]
Hi @iMicknl.
Can't find back in the log. Closing it for now, will re-open if needed.
