### ISSUE TITLE
Regression in 2.6.0 for "AtlanticPassAPCHeatingAndCoolingZone" device

### ISSUE THREAD

**Issue by gerardsamara** [iMicknl/ha-tahoma#517]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Hello ,

Following the update to 2.6.0 , the following errors are displayed in the log

`2021-08-10 18:47:47 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform tahoma
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 587, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 710, in add_to_platform_finish
await self.async_added_to_hass()
File "/config/custom_components/tahoma/climate_devices/atlantic_pass_apc_heating_and_cooling_zone.py", line 76, in async_added_to_hass
base_url = self.get_base_device_url()
AttributeError: 'AtlanticPassAPCHeatingAndCoolingZone' object has no attribute 'get_base_device_url'
2021-08-10 18:47:47 ERROR (MainThread) [homeassistant.components.climate] Error while setting up tahoma platform for climate
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 587, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 710, in add_to_platform_finish
await self.async_added_to_hass()
File "/config/custom_components/tahoma/climate_devices/atlantic_pass_apc_heating_and_cooling_zone.py", line 76, in async_added_to_hass
base_url = self.get_base_device_url()
AttributeError: 'AtlanticPassAPCHeatingAndCoolingZone' object has no attribute 'get_base_device_url'`

![Capture zone1 developer tools](https://user-images.githubusercontent.com/69084518/128990107-52b555c2-1b11-4a66-9339-2e0518bf5866.JPG)
![Capture tahoma zone1 lovelace](https://user-images.githubusercontent.com/69084518/128990121-570612e0-086b-4bdb-9793-1b4f47c86fdc.JPG)

The temperature now is missing for this device in Lovelace

Please can you have a look ?
Thank you

### What version of this integration (ha-tahoma) has the issue?

2.6.0

### What version of Home Assistant Core has the issue?

2021.8.4

### Which gateway / hub do you use?

Cozytouch

### Device model

R002412300 by Atlantic Group 

### Device type

Firmware: io:AtlanticPassAPCHeatPumpMainComponent

### Relevant log output

```shell
2021-08-10 18:47:47 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform tahoma
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 587, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 710, in add_to_platform_finish
await self.async_added_to_hass()
File "/config/custom_components/tahoma/climate_devices/atlantic_pass_apc_heating_and_cooling_zone.py", line 76, in async_added_to_hass
base_url = self.get_base_device_url()
AttributeError: 'AtlanticPassAPCHeatingAndCoolingZone' object has no attribute 'get_base_device_url'
2021-08-10 18:47:47 ERROR (MainThread) [homeassistant.components.climate] Error while setting up tahoma platform for climate
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 587, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 710, in add_to_platform_finish
await self.async_added_to_hass()
File "/config/custom_components/tahoma/climate_devices/atlantic_pass_apc_heating_and_cooling_zone.py", line 76, in async_added_to_hass
base_url = self.get_base_device_url()
AttributeError: 'AtlanticPassAPCHeatingAndCoolingZone' object has no attribute 'get_base_device_url'
```

**Comment by gerardsamara** [comment]
Hi ,

I did not see at first that the entities have been duplicated as per this screenshot

![Capture ha tahoma](https://user-images.githubusercontent.com/69084518/128991788-063b21ee-0d43-49bb-acef-c4da59cb68de.JPG)

**Comment by tetienne** [comment]
Hi thx for reporting this.

It will been fixed with https://github.com/iMicknl/ha-tahoma/pull/516

**Comment by iMicknl** [comment]
Please update to 2.6.1, which should contain this fix. Thanks!

**Comment by gerardsamara** [comment]
I have updated and the errors are gone
Thank you for the fix

Do I need to delete and re-install the ha-tahoma custom component+integration as I have duplicated devices as per the enclosed screenshot ( to have a cleaner configuration) ?

![Capture ha tahoma](https://user-images.githubusercontent.com/69084518/129031347-cc26cb84-8745-4265-9210-293229c55043.JPG)

**Comment by gerardsamara** [comment]
Done.
Everything ok
Thank you

⁣Télécharger BlueMail pour Android ​

Le 11 août 2021 à 15:04, à 15:04, Thibaut ***@***.***> a écrit:
***@***.*** Yes you can reinstall the component, we have perform a
