### ISSUE TITLE
Errors on startup

### ISSUE THREAD

**Issue by fredericseiler** [iMicknl/ha-tahoma#551]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

On startup, I got some errors, and the "heat" entity from my air-to-water heat pump is not found anymore.

### What version of this integration (ha-tahoma) has the issue?

2.7.0

### What version of Home Assistant Core has the issue?

core-2021.9.4

### Which gateway / hub do you use?

Hi-Kumo (Europe)

### Device model

not displayed (HitachiHeatingSystem / HitachiAirToWaterMainComponent)

### Device type

not displayed (based on several modbus:Yutaki*)

### Additional information

Before:
<img width="325" alt="2021-09-07-08-53-25 Google Chrome Add support for Hitachi Yutaki S heat pump (modbusYutakiMainComponent) · Issue #519 · iMicknlha-tahoma" src="https://user-images.githubusercontent.com/954168/132298068-4cdf2863-ee8e-41e1-a60a-caa9a5e7fb47.png">

After:
<img width="339" alt="2021-09-07-08-51-44 Google Chrome Configuration - Home Assistant" src="https://user-images.githubusercontent.com/954168/132297877-96f40d4e-18f4-40c3-b093-9f1903a38c56.png">

### Relevant log output

```shell
2021-09-07 08:30:02 ERROR (MainThread) [homeassistant.components.switch] Error while setting up tahoma platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/tahoma/switch.py", line 50, in async_setup_entry
[
TypeError: 'NoneType' object is not iterable

2021-09-07 08:30:02 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform tahoma
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 498, in _async_add_entity
capabilities=entity.capability_attributes,
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 226, in capability_attributes
ATTR_HVAC_MODES: self.hvac_modes,
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 341, in hvac_modes
return self._attr_hvac_modes
AttributeError: 'HitachiAirToWaterHeatingZone' object has no attribute '_attr_hvac_modes'

2021-09-07 08:30:02 ERROR (MainThread) [homeassistant.components.climate] Error while setting up tahoma platform for climate
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 498, in _async_add_entity
capabilities=entity.capability_attributes,
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 226, in capability_attributes
ATTR_HVAC_MODES: self.hvac_modes,
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 341, in hvac_modes
return self._attr_hvac_modes
AttributeError: 'HitachiAirToWaterHeatingZone' object has no attribute '_attr_hvac_modes'
```

**Comment by tetienne** [comment]
Thx for reporting this. I’ve opened the PR to fix your issue. It should be soon released.
