### ISSUE TITLE
Remaining errors in HA logs in ha-tahoma V2.7.1

### ISSUE THREAD

**Issue by gerardsamara** [iMicknl/ha-tahoma#554]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Remaining errors in HA log with ha-tahoma V2.7.1

```
2021-09-07 17:43:19 INFO (MainThread) [homeassistant.setup] Setting up tahoma
2021-09-07 17:43:19 INFO (MainThread) [homeassistant.setup] Setup of domain tahoma took 0.0 seconds
2021-09-07 17:43:20 WARNING (MainThread) [homeassistant.components.sensor] custom_components.tahoma.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author.
2021-09-07 17:43:20 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.tahoma
2021-09-07 17:43:20 WARNING (MainThread) [custom_components.tahoma.climate_devices.atlantic_pass_apc_heating_and_cooling_zone] Temperature sensor could not be found for entity Zone 1
2021-09-07 17:43:20 ERROR (MainThread) [homeassistant.components.switch] Error while setting up tahoma platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/tahoma/switch.py", line 50, in async_setup_entry
[
TypeError: 'NoneType' object is not iterable`
```

### What version of this integration (ha-tahoma) has the issue?

2.7.1

### What version of Home Assistant Core has the issue?

Core-2021.9.4

### Which gateway / hub do you use?

Cozytouch

### Device model

R002412300 by Atlantic Group Firmware: C667208

### Device type

Atlantic Firmware: 2021.3.4

### Additional information

In addition the temperature is not displayed anymore for heat chart

![Capture tahoma 271](https://user-images.githubusercontent.com/69084518/132456629-c7c7293d-814d-4a6b-af98-c43117989f54.PNG)

### Relevant log output

```shell
2021-09-07 17:43:19 INFO (MainThread) [homeassistant.setup] Setting up tahoma
2021-09-07 17:43:19 INFO (MainThread) [homeassistant.setup] Setup of domain tahoma took 0.0 seconds
2021-09-07 17:43:20 WARNING (MainThread) [homeassistant.components.sensor] custom_components.tahoma.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author.
2021-09-07 17:43:20 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.tahoma
2021-09-07 17:43:20 WARNING (MainThread) [custom_components.tahoma.climate_devices.atlantic_pass_apc_heating_and_cooling_zone] Temperature sensor could not be found for entity Zone 1
2021-09-07 17:43:20 ERROR (MainThread) [homeassistant.components.switch] Error while setting up tahoma platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/tahoma/switch.py", line 50, in async_setup_entry
[
TypeError: 'NoneType' object is not iterable
```

**Comment by tetienne** [comment]
Thx for this report. I guess you haven’t any covers? About the warning, this one has been fixed with https://github.com/iMicknl/ha-tahoma/pull/553 and I have now fixed your error with. 

Both fixes will be available with the next release.

**Comment by gerardsamara** [comment]
Thanks for your quick fix.
No i have not cover


⁣Télécharger BlueMail pour Android ​

Le 8 sept. 2021 à 08:51, à 08:51, Thibaut ***@***.***> a écrit:
