### ISSUE TITLE
Error during loading integration

### ISSUE THREAD

**Issue by Tecotix** [iMicknl/ha-tahoma#557]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

During the start the following message appears in the log:

```
Logger: homeassistant
Source: custom_components/tahoma/sensor.py:342
Integration: Overkiz (by Somfy)
First occurred: 08:54:17 (7 occurrences)
Last logged: 08:57:15

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 464, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 498, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in _stringify_state
    state = self.state
  File "/config/custom_components/tahoma/sensor.py", line 342, in state
    state = self.device.states.get(self.entity_description.key)
AttributeError: 'list' object has no attribute 'get'
```

Same if I close or open the shutters. 

![grafik](https://user-images.githubusercontent.com/78791840/132639723-c94781da-1906-42d0-8397-209dcabdb82c.png)

### What version of this integration (ha-tahoma) has the issue?

2.7.1

### What version of Home Assistant Core has the issue?

core-2021.9.4

### Which gateway / hub do you use?

Tahoma Switch

### Device model

Tahoma Basic

### Device type

2021.2.4

### Relevant log output

```shell
Logger: homeassistant
Source: custom_components/tahoma/sensor.py:342
Integration: Overkiz (by Somfy)
First occurred: 08:54:17 (7 occurrences)
Last logged: 08:57:15

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 464, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 498, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in _stringify_state
    state = self.state
  File "/config/custom_components/tahoma/sensor.py", line 342, in state
    state = self.device.states.get(self.entity_description.key)
AttributeError: 'list' object has no attribute 'get'
```

**Comment by cxnull** [comment]
I have the exact same problem on a TaHoma Switch (on which I have scenes activated as per [the instructions specific to this device](https://github.com/iMicknl/ha-tahoma#tahoma-switch))


The covers do work when manually activating them via entity cards for example, but this error is thrown every time. It also causes any automation to stop when it is encountered, making automations broken if there is one of these actions somewhere not at the very end of a sequence of actions.

- What version of this integration (ha-tahoma) has the issue?
2.7.2

- What version of Home Assistant Core has the issue?
core-2021.9.6

- Which gateway / hub do you use?
Tahoma Switch

- Device model
?

- Device type
?

- Additional information
I'd be glad to provide any additional information if needed

- Relevant log output
```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/tahoma/sensor.py:348
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:28:17 PM (1 occurrences)
Last logged: 12:28:17 PM

[547886953760] 'list' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/config/custom_components/tahoma/cover_devices/vertical_cover.py", line 128, in async_close_cover
    await self.executor.async_execute_command(
  File "/config/custom_components/tahoma/executor.py", line 83, in async_execute_command
    await self.coordinator.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 165, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 464, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 498, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in _stringify_state
    state = self.state
  File "/config/custom_components/tahoma/sensor.py", line 348, in state
    state = self.device.states.get(self.entity_description.key)
AttributeError: 'list' object has no attribute 'get'
```

**Comment by tetienne** [comment]
@Tecotix @cxnull Thx for reporting this issue. I guess your device are stateless (RTS) ?

**Comment by cxnull** [comment]
@tetienne thank you for your quick reply! In my case, most devices are stateful (io): they report their current position, among others. I have one stateless device (RTS). I'm seing the same behavior on both types of devices: as soon as I request motion they actually do start moving, but then the error is thrown, and in the case of an automation, the automation halts at that point.

**Comment by Tecotix** [comment]
In my case, all my devices are stateful (io)

**Comment by cxnull** [comment]
Just tested the new release, and it works!
- I no longer see error notification or log entries when moving covers
- Automations involving several covers in sequence no longer halt because of errors

Thank you guys!!!

**Comment by tetienne** [comment]
@cxnull Thank for the feedback, I’m glad your issue is now gone.
