### ISSUE TITLE
Config entry has already been setup

### ISSUE THREAD

**Issue by tetienne** [iMicknl/ha-tahoma#560]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Disable the integration, and enable it. 

### What version of this integration (ha-tahoma) has the issue?

2.7.1

### What version of Home Assistant Core has the issue?

2021.9.5

### Which gateway / hub do you use?

Somfy Tahoma

### Device model

N/A

### Device type

N/A

### Relevant log output

```shell
2021-09-10 13:30:37 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry thibaut.etienne@protonmail.ch for binary_sensor
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/homeassistant/components/binary_sensor/__init__.py", line 148, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/local/lib/python3.9/site-packages/homeassistant/helpers/entity_component.py", line 164, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2021-09-10 13:30:37 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry thibaut.etienne@protonmail.ch for sensor
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/homeassistant/components/sensor/__init__.py", line 121, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/local/lib/python3.9/site-packages/homeassistant/helpers/entity_component.py", line 164, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
```

**Comment by iMicknl** [comment]
I recall I have seen the same issue when you reload the integration.
