### ISSUE TITLE
Add more state sensors for DomesticHotWaterProduction (io:AtlanticDomesticHotWaterProductionV2_CE_FLAT_C2_IOComponent)

### ISSUE THREAD

**Issue by jncanches** [iMicknl/ha-tahoma#568]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

The integration works well with cozytouch. I have a Thermor water heater which is well detected.
I can change mode etc

But an important data is missing. This data exists in the cozytouch custom component (https://github.com/Cyr-ius/hass-cozytouch). It is a boolean called energy_demand (io:OperatingModeCapabilitiesState energy_demand) which is set to true when water heater is heating.
I think it is beacause power is not retrieved from cozytouch data.
Some other data are missing like core:V40WaterVolumeEstimationState which is the hot water volume already consumed.

### What version of this integration (ha-tahoma) has the issue?

2.7.2

### What version of Home Assistant Core has the issue?

2021.9.6

### Which gateway / hub do you use?

CozyTouch

### Device model

DomesticHotWaterProduction

### Device type

E722804

**Comment by jncanches** [comment]
I tried to use tahoma.get_execution_history service but nothing is logged in home-assistant.log

**Comment by tetienne** [comment]
```JSON
{
  "commands": [
    {
      "commandName": "advancedRefresh",
      "nparams": 1
    },
    {
      "commandName": "delayedStopIdentify",
      "nparams": 1
    },
    {
      "commandName": "getName",
      "nparams": 0
    },
    {
      "commandName": "identify",
      "nparams": 0
    },
    {
      "commandName": "refreshAbsenceEndDate",
      "nparams": 0
    },
    {
      "commandName": "refreshAbsenceMode",
      "nparams": 0
    },
    {
      "commandName": "refreshAbsenceStartDate",
      "nparams": 0
    },
    {
      "commandName": "refreshBoostEndDate",
      "nparams": 0
    },
    {
      "commandName": "refreshBoostMode",
      "nparams": 0
    },
    {
      "commandName": "refreshBoostStartDate",
      "nparams": 0
    },
    {
      "commandName": "refreshBottomTankWaterTemperature",
      "nparams": 0
    },
    {
      "commandName": "refreshManufacturerName",
      "nparams": 0
    },
    {
      "commandName": "refreshMiddleWaterTemperatureIn",
      "nparams": 0
    },
    {
      "commandName": "refreshTargetTemperature",
      "nparams": 0
    },
    {
      "commandName": "refreshWaterConsumption",
      "nparams": 0
    },
    {
      "commandName": "refreshWaterTargetTemperature",
      "nparams": 0
    },
    {
      "commandName": "refreshWaterTemperature",
      "nparams": 0
    },
    {
      "commandName": "setAbsenceEndDate",
      "nparams": 1
    },
    {
      "commandName": "setAbsenceMode",
      "nparams": 1
    },
    {
      "commandName": "setAbsenceStartDate",
      "nparams": 1
    },
    {
      "commandName": "setBoostEndDate",
      "nparams": 1
    },
    {
      "commandName": "setBoostMode",
      "nparams": 1
    },
    {
      "commandName": "setBoostStartDate",
      "nparams": 1
    },
    {
      "commandName": "setComfortTargetTemperature",
      "nparams": 1
    },
    {
      "commandName": "setDateTime",
      "nparams": 1
    },
    {
      "commandName": "setEcoTargetTemperature",
      "nparams": 1
    },
    {
      "commandName": "setExpectedNumberOfShower",
      "nparams": 1
    },
    {
      "commandName": "setFrostProtectionTargetTemperature",
      "nparams": 1
    },
    {
      "commandName": "setName",
      "nparams": 1
    },
    {
      "commandName": "setTargetDHWTemperature",
      "nparams": 1
    },
    {
      "commandName": "setTargetTemperature",
      "nparams": 1
    },
    {
      "commandName": "setWaterTargetTemperature",
      "nparams": 1
    },
    {
      "commandName": "setWaterTemperature",
      "nparams": 1
    },
    {
      "commandName": "startIdentify",
      "nparams": 0
    },
    {
      "commandName": "stopIdentify",
      "nparams": 0
    },
    {
      "commandName": "wink",
      "nparams": 1
    },
    {
      "commandName": "refreshExpectedNumberOfShower",
      "nparams": 0
    },
    {
      "commandName": "pairOneWayController",
      "nparams": 2
    },
    {
      "commandName": "refreshAntiLegionellosis",
      "nparams": 0
    },
    {
      "commandName": "refreshAwayModeDuration",
      "nparams": 0
    },
    {
      "commandName": "refreshBoilerInstallationOption",
      "nparams": 0
    },
    {
      "commandName": "refreshBoostModeDuration",
      "nparams": 0
    },
    {
      "commandName": "refreshCurrentOperatingMode",
      "nparams": 0
    },
    {
      "commandName": "refreshDHWCapacity",
      "nparams": 0
    },
    {
      "commandName": "refreshDHWError",
      "nparams": 0
    },
    {
      "commandName": "refreshDHWMode",
      "nparams": 0
    },
    {
      "commandName": "refreshElectricalExtraManagement",
      "nparams": 0
    },
    {
      "commandName": "refreshExtractionOption",
      "nparams": 0
    },
    {
      "commandName": "refreshInstallation",
      "nparams": 0
    },
    {
      "commandName": "refreshMiddleWaterTemperature",
      "nparams": 0
    },
    {
      "commandName": "refreshOperatingModeCapabilities",
      "nparams": 0
    },
    {
      "commandName": "refreshOperatingRange",
      "nparams": 0
    },
    {
      "commandName": "refreshOperatingTime",
      "nparams": 0
    },
    {
      "commandName": "refreshProgrammingSlots",
      "nparams": 0
    },
    {
      "commandName": "refreshRateManagement",
      "nparams": 0
    },
    {
      "commandName": "refreshSmartGridOption",
      "nparams": 0
    },
    {
      "commandName": "setAntiLegionellosis",
      "nparams": 1
    },
    {
      "commandName": "setAwayModeDuration",
      "nparams": 1
    },
    {
      "commandName": "setBoilerInstallationOption",
      "nparams": 1
    },
    {
      "commandName": "setBoostModeDuration",
      "nparams": 1
    },
    {
      "commandName": "setCurrentOperatingMode",
      "nparams": 1
    },
    {
      "commandName": "setDHWMode",
      "nparams": 1
    },
    {
      "commandName": "setElectricalExtraManagement",
      "nparams": 1
    },
    {
      "commandName": "setExtractionOption",
      "nparams": 1
    },
    {
      "commandName": "setHaltedTargetTemperature",
      "nparams": 1
    },
    {
      "commandName": "setInstallation",
      "nparams": 1
    },
    {
      "commandName": "setOperatingRange",
      "nparams": 1
    },
    {
      "commandName": "setProgrammingSlots",
      "nparams": 1
    },
    {
      "commandName": "setRateManagement",
      "nparams": 1
    },
    {
      "commandName": "setSmartGridOption",
      "nparams": 1
    },
    {
      "commandName": "unpairAllOneWayControllers",
      "nparams": 0
    },
    {
      "commandName": "unpairOneWayController",
      "nparams": 2
    }
  ],
  "states": [
    {
      "type": "DataState",
      "qualifiedName": "core:AbsenceEndDateState"
    },
    {
      "type": "DataState",
      "qualifiedName": "core:AbsenceStartDateState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:BoostElectricPowerConsumptionState"
    },
    {
      "type": "DataState",
      "qualifiedName": "core:BoostEndDateState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:BoostModeDurationState"
    },
    {
      "type": "DataState",
      "qualifiedName": "core:BoostStartDateState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:BottomTankWaterTemperatureState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:ComfortTargetTemperatureState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:ControlWaterTargetTemperatureState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:DHWPSoftwareVersionState"
    },
    {
      "type": "DataState",
      "qualifiedName": "core:DateTimeState"
    },
    {
      "type": "DiscreteState",
      "values": [
        "good",
        "low",
        "normal",
        "verylow"
      ],
      "qualifiedName": "core:DiscreteRSSILevelState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:EcoTargetTemperatureState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:ExpectedNumberOfShowerState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:FrostProtectionTargetTemperatureState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:HaltedTargetTemperatureState"
    },
    {
      "type": "DataState",
      "qualifiedName": "core:HeatingStatusState"
    },
    {
      "type": "DataState",
      "qualifiedName": "core:ManufacturerNameState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:MaximalShowerManualModeState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:MaximalTemperatureManualModeState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:MiddleWaterTemperatureInState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:MinimalShowerManualModeState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:MinimalTemperatureManualModeState"
    },
    {
      "type": "DataState",
      "qualifiedName": "core:NameState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:NumberOfShowerRemainingState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:NumberOfTankState"
    },
    {
      "type": "DiscreteState",
      "values": [
        "antifreeze",
        "auto",
        "away",
        "eco",
        "frostprotection",
        "manual",
        "max",
        "normal",
        "off",
        "on",
        "prog",
        "program",
        "boost"
      ],
      "qualifiedName": "core:OperatingModeState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:PowerHeatElectricalInState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:PriorityLockTimerState"
    },
    {
      "type": "DataState",
      "qualifiedName": "core:ProgrammingAvailableState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:RSSILevelState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:SecuredPositionTemperatureState"
    },
    {
      "type": "DiscreteState",
      "values": [
        "available",
        "unavailable"
      ],
      "qualifiedName": "core:StatusState"
    },
    {
      "type": "DataState",
      "qualifiedName": "core:StopRelaunchState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:TargetDHWTemperatureState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:TargetTemperatureState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:TemperatureState"
    },
    {
      "type": "DataState",
      "qualifiedName": "core:V40WaterVolumeEstimationState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:VersionState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:WaterConsumptionState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:WaterTargetTemperatureState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "core:WaterTemperatureState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "io:AntiLegionellosisState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "io:AwayModeDurationState"
    },
    {
      "type": "DiscreteState",
      "values": [
        "boilerOptimising",
        "boilerPriority",
        "heatPumpOptimising",
        "heatPumpPriority"
      ],
      "qualifiedName": "io:BoilerInstallationOptionState"
    },
    {
      "type": "DiscreteState",
      "values": [
        "off",
        "on",
        "prog"
      ],
      "qualifiedName": "io:DHWAbsenceModeState"
    },
    {
      "type": "DiscreteState",
      "values": [
        "off",
        "on",
        "prog"
      ],
      "qualifiedName": "io:DHWBoostModeState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "io:DHWCapacityState"
    },
    {
      "type": "DataState",
      "qualifiedName": "io:DHWErrorState"
    },
    {
      "type": "DiscreteState",
      "values": [
        "autoMode",
        "manualEcoActive",
        "manualEcoInactive"
      ],
      "qualifiedName": "io:DHWModeState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "io:ElectricBoosterOperatingTimeState"
    },
    {
      "type": "DiscreteState",
      "values": [
        "auto",
        "deactive"
      ],
      "qualifiedName": "io:ElectricalExtraManagementState"
    },
    {
      "type": "DiscreteState",
      "values": [
        "fastExtractionSpeed",
        "lowExtractionSpeed",
        "noExtraction"
      ],
      "qualifiedName": "io:ExtractionOptionState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "io:HeatPumpOperatingTimeState"
    },
    {
      "type": "DiscreteState",
      "values": [
        "extraBoiler",
        "extraSolar",
        "onlyThermodynamic"
      ],
      "qualifiedName": "io:InstallationState"
    },
    {
      "type": "ContinuousState",
      "qualifiedName": "io:MiddleWaterTemperatureState"
    },
    {
      "type": "DataState",
      "qualifiedName": "io:OperatingModeCapabilitiesState"
    },
    {
      "type": "DiscreteState",
      "values": [
        "pac24h_elec24h",
        "pacProg_elecProg"
      ],
      "qualifiedName": "io:OperatingRangeState"
    },
    {
      "type": "DataState",
      "qualifiedName": "io:PowerConsumptionFanState"
    },
    {
      "type": "DataState",
      "qualifiedName": "io:PowerHeatElectricalState"
    },
    {
      "type": "DataState",
      "qualifiedName": "io:PowerHeatPumpState"
    },
    {
      "type": "DiscreteState",
      "values": [
        "comfortLevel1",
        "comfortLevel2",
        "comfortLevel3",
        "comfortLevel4",
        "environmentProtection",
        "humanProtection",
        "userLevel1",
        "userLevel2"
      ],
      "qualifiedName": "io:PriorityLockLevelState"
    },
    {
      "type": "DiscreteState",
      "values": [
        "LSC",
        "SAAC",
        "SFC",
        "UPS",
        "externalGateway",
        "localUser",
        "myself",
        "rain",
        "security",
        "temperature",
        "timer",
        "user",
        "wind"
      ],
      "qualifiedName": "io:PriorityLockOriginatorState"
    },
    {
      "type": "DataState",
      "qualifiedName": "io:ProgrammingSlotsState"
    },
    {
      "type": "DiscreteState",
      "values": [
        "forbidden",
        "no",
        "recommended",
        "unsuitable",
        "wanted"
      ],
      "qualifiedName": "io:RateManagementState"
    },
    {
      "type": "DiscreteState",
      "values": [
        "active",
        "deactive"
      ],
      "qualifiedName": "io:SmartGridOptionState"
    }
  ],
  "dataProperties": [
    {
      "value": "500",
      "qualifiedName": "core:identifyInterval"
    }
  ],
  "widgetName": "DomesticHotWaterProduction",
  "uiProfiles": [
    "StatefulDHWThermostat",
    "DHWThermostat",
    "StatefulThermostatWithSensor",
    "StatefulThermostat",
    "Thermostat",
    "WaterConsumption"
  ],
  "uiClass": "WaterHeatingSystem",
  "qualifiedName": "io:AtlanticDomesticHotWaterProductionV2_CE_FLAT_C2_IOComponent",
  "type": "ACTUATOR"
}
```

**Comment by jncanches** [comment]
I don't understand what I have to do with that json ?

**Comment by tetienne** [comment]
Sorry, it was for the history of this issue. It just the description returned by Overkiz API. I will add soon your two requested sensors.

**Comment by jncanches** [comment]
Wonderful ! I would be pleased to test it :) Thanks

**Comment by tetienne** [comment]
By the way, @jncanches V40WaterVolumeEstimationState is already supported. You should have normally a sensor for it.

**Comment by tetienne** [comment]
@iMicknl That’s the first time we meet this kind of state. Type 11 means JSON object.

`{'name': 'io:OperatingModeCapabilitiesState', 'type': 11, 'value': {'relaunch': 1, 'absence': 1, 'rateManagement': 1, 'energyDemandStatus': 0}}`

@jncanches `relaunch`, `absence`, `rateManagement` and `energyDemandStatus` all means something for you?

**Comment by jncanches** [comment]
absence is probably "away mode", energyDemandStatus seems to be the data I talked about in my first post : the water heater is currently heating the water.
For rateManagement and relaunch, I don't know see what it can be...

**Comment by jncanches** [comment]
> By the way, @jncanches V40WaterVolumeEstimationState is already supported. You should have normally a sensor for it.

My bad, you are right, thank you for this one :)

**Comment by jncanches** [comment]
For now, I have reverted to ha:cozytouch custom-component. It is a lot less reactive but it offers all the json data available.
Will try this one again on next release, or if you need tests.

**Comment by tetienne** [comment]
Sure, I will try to find some free times to add your sensor. I will ping you once done.

**Comment by jncanches** [comment]
Hi @iMicknl 

Thanks for this fix. I tried it. 
I have the entity binary_sensor.dhwp_actuator_energy_demand_status but it is unavailable.

Logs show the following:

`2021-10-29 23:52:16 ERROR (MainThread) [custom_components.cozytouch.sensor] Device data no retrieve All House Dhw Cumulated Electrical Energy Consumption IO System Device Sensor
2021-10-29 23:52:41 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 456, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 489, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 462, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 178, in state
    return STATE_ON if self.is_on else STATE_OFF
  File "/config/custom_components/tahoma/binary_sensor.py", line 125, in is_on
    return self.entity_description.is_on(state.value)
  File "/config/custom_components/tahoma/binary_sensor.py", line 81, in <lambda>
    is_on=lambda state: state["energyDemandStatus"] == 0,
KeyError: 'energyDemandStatus'
2021-10-29 23:52:46 ERROR (MainThread) [custom_components.cozytouch.sensor] Device data no retrieve All House Dhw Cumulated Electrical Energy Consumption IO System Device Sensor
2021-10-29 23:52:46 ERROR (MainThread) [custom_components.cozytouch.water_heater] Device data no retrieve All House Domestichotwaterproduction`

I will be pleased to test any fix if you need it !

**Comment by iMicknl** [comment]
@jncanches could you turn on debug mode and share your full log?

**Comment by fritanga** [comment]
Got the same error till there is an enery_demand change. Ater that it works, but with inverted state.
is_on=lambda state: state["energyDemandStatus"] == 0 should check for 1 instead of 0.

The other two sensors added work, but u coded them as sensor.DEVICE_CLASS_TIMESTAMP.  They really store the value in total hours in pure electrical o heatpump mode, so they are close to be a utility meter than timestamp sensor, perhaps its better to add them as attributtes or sensors without  a device_class.

**Comment by iMicknl** [comment]
Could you try the new version?  https://github.com/iMicknl/ha-tahoma/archive/refs/heads/fix/568.zip

Any feedback? :)

**Comment by fritanga** [comment]
> @jncanches could you turn on debug mode and share your full log?
> Could you try the new version? https://github.com/iMicknl/ha-tahoma/archive/refs/heads/fix/568.zip
> 
> Any feedback? :)

[tahoma.log](https://github.com/iMicknl/ha-tahoma/files/7445318/tahoma.log)

Same error till a change. As u can see in log there first time u connect to the device it has status of energy demand but with a slightly differente format
 State(name='io:OperatingModeCapabilitiesState', type=<DataType.JSON_OBJECT: 11>, value={'relaunch': 1, 'absence': 1, 'rate_management': 0, 'energy_demand_status': 1}),

**Comment by jncanches** [comment]
Exactly the same here

**Comment by iMicknl** [comment]
@jncanches @fritanga could you try again. Apparently the fixes weren't pushed correctly, thus you were testing the same old code :D.

**Comment by fritanga** [comment]
> @jncanches @fritanga could you try again. Apparently the fixes weren't pushed correctly, thus you were testing the same old code :D.

Works without errors!
Thanks a lot :)

**Comment by jncanches** [comment]
Thank you very much !

**Comment by jncanches** [comment]
One question please. Is realase 2.9.2 does include this fix already ?

**Comment by tetienne** [comment]
@jncanches no, it Will be include with the next one
