### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by edouardmenayde** [iMicknl/ha-tahoma#583]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

I get a bad credentials error when connecting to nexity (eugenie) platform.
I am pretty sure my credentials are okay : 
- Tried changing them
- Tried to reproduce the call in postman and got the same error

Has anyone struggled with this too ?

Ps : Not sure if i should post this here or in python-tahoma-api github repo...
Sorry if it's not meant to be posted here.

### What version of this integration (ha-tahoma) has the issue?

2.8.1

### What version of Home Assistant Core has the issue?

core-2021.9.7

### Which gateway / hub do you use?

Nexity

### Device model

?

### Device type

?

**Comment by iMicknl** [comment]
If you are using Home Assistant, this place is the right place to report this issue.

Which app or website do you use to login to your Nexity device normally? And did Home Assistant discover your hub automatically, after you installed this integration? I think you are our first Nexity user, thus we need to see if it can be supported.

**Comment by iMicknl** [comment]
If I decompile the [Eugénie](https://play.google.com/store/apps/details?id=fr.nexity.eugenie&hl=nl&gl=US) (fr.nexity.eugenie) Android app, I see the same URL as the one we use in our integration. Could it be that you are using a different app / platform?

```java
.field public static final OVERKIZ_API_URL:Ljava/lang/String; = "https://ha106-1.overkiz.com/enduser-mobile-web/enduserAPI"
```

**Comment by edouardmenayde** [comment]
I am indeed using this app (iOS version but it should not matter here).-

**Comment by edouardmenayde** [comment]
HA did not discover the hub automatically after installation

**Comment by edouardmenayde** [comment]
The endpoint is the right one indeed : I proxied my calls to the api through proxy man and it's the same one as you extracted

**Comment by iMicknl** [comment]
Would you be able to work with me [via Discord](https://discord.gg/gDSNf8MKf7) (iMick #1903) so we can debug this. Easiest would be if you could temporary change your password and send your credentials, so I can do some live debugging on my machine.

I am not sure if we can resolve this, if they are not accepting your credentials :(. Could you check which request they do for a login? If they are adding a client_id perhaps, instead of just a user/pass.

**Comment by fafifi** [comment]
> 
> 
> https://github.com/iMicknl/ha-tahoma/archive/refs/heads/feature/support_custom_authentication.zip
> 
> This should solve the issue with Nexity. Will be in the next releases.

Hello,

I just tried your path, the problem is still present for me.
I get the following message: Incorrect password or username
However I am of course on the identifiers to inform.

I use the eugénie app on Android.

Thanks for your help,
Available if you need additional information.

**Comment by GHTix** [comment]
I've copy tahoma-master in my custom_components

Error message changed
![Capture2](https://user-images.githubusercontent.com/13834583/138119604-38403743-1e26-4667-a542-77989baa9f69.PNG)
```
2021-10-20 17:00:37 INFO (SyncWorker_2) [homeassistant.util.package] Attempting install of pyhoma==0.5.22
2021-10-20 17:01:07 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for tahoma doing I/O at custom_components/tahoma/config_flow.py, line 48: await client.login()
2021-10-20 17:01:07 ERROR (MainThread) [custom_components.tahoma.config_flow] An HTTP Client raised an unhandled exception: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/tahoma/config_flow.py, line 48: await client.login()
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/botocore/httpsession.py", line 254, in send
self._proxy_managers[proxy_url] = proxy_manager
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
conn.request(method, url, **httplib_request_kw)
File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
super(HTTPConnection, self).request(method, url, body=body, headers=headers)
File "/usr/local/lib/python3.9/http/client.py", line 1279, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/usr/local/lib/python3.9/site-packages/botocore/awsrequest.py", line 91, in _send_request
self.response_class = self._original_response_cls
File "/usr/local/lib/python3.9/http/client.py", line 1290, in _send_request
self.putrequest(method, url, **skips)
File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 219, in putrequest
return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 151, in protected_loop_func
check_loop()
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 140, in check_loop
raise RuntimeError(
RuntimeError: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/tahoma/config_flow.py, line 48: await client.login()
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/tahoma/config_flow.py", line 84, in async_step_user
return await self.async_validate_input(user_input)
File "/config/custom_components/tahoma/config_flow.py", line 48, in async_validate_input
await client.login()
File "/usr/local/lib/python3.9/site-packages/pyhoma/client.py", line 127, in login
sso_token = await self.nexity_login()
File "/usr/local/lib/python3.9/site-packages/pyhoma/client.py", line 192, in nexity_login
client = boto3.client(
File "/usr/local/lib/python3.9/site-packages/boto3/__init__.py", line 93, in client
return _get_default_session().client(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/boto3/session.py", line 258, in client
return self._session.create_client(
File "/usr/local/lib/python3.9/site-packages/botocore/session.py", line 826, in create_client
elif self._missing_cred_vars(aws_access_key_id,
File "/usr/local/lib/python3.9/site-packages/botocore/session.py", line 430, in get_credentials
have already been loaded, this will return the cached
File "/usr/local/lib/python3.9/site-packages/botocore/credentials.py", line 1969, in load_credentials
"""
File "/usr/local/lib/python3.9/site-packages/botocore/credentials.py", line 1022, in load
def __init__(self, iam_role_fetcher):
File "/usr/local/lib/python3.9/site-packages/botocore/utils.py", line 474, in retrieve_iam_role_credentials
if self._user_agent is not None:
File "/usr/local/lib/python3.9/site-packages/botocore/utils.py", line 368, in _fetch_metadata_token
timeout=self._timeout,
File "/usr/local/lib/python3.9/site-packages/botocore/httpsession.py", line 299, in send
if proxy_url:
botocore.exceptions.HTTPClientError: An HTTP Client raised an unhandled exception: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/tahoma/config_flow.py, line 48: await client.login()
```
