### ISSUE TITLE
Error with new version

### ISSUE THREAD

**Issue by legantois** [iMicknl/ha-tahoma#649]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Since last update I have errors in log but it seems that everything is still working

### What version of this integration (ha-tahoma) has the issue?

Home Assistant 2021.10.6

### What version of Home Assistant Core has the issue?

Version 	core-2021.10.6

### Which gateway / hub do you use?

Tahoma Switch

### Home Assistant log

```shell
2021-11-05 00:13:22 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration tahoma which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-05 00:13:28 WARNING (MainThread) [pyhoma.enums] Unsupported value 98 has been returned for <enum 'GatewayType'>
2021-11-05 00:13:28 ERROR (MainThread) [homeassistant.components.number] Error adding entities for domain number with platform tahoma
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 587, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 682, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 456, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 489, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 462, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 130, in state
    return self.value
  File "/config/custom_components/tahoma/number.py", line 65, in value
    return self.device.states.get(self.entity_description.key).value
AttributeError: 'NoneType' object has no attribute 'value'
```

**Comment by tetienne** [comment]
Can you please update to 2.9.3 if not already done?

**Comment by legantois** [comment]
Did th eupdate

no more errors - many thanks. Some warning though

2021-11-13 10:03:14 WARNING (MainThread) [pyhoma.enums] Unsupported value 98 has been returned for <enum 'GatewayType'>
2021-11-13 12:19:46 WARNING (MainThread) [pyhoma.enums] Unsupported value SetupTriggerTriggeredEvent has been returned for <enum 'EventName'>
2021-11-13 12:27:16 WARNING (MainThread) [pyhoma.enums] Unsupported value SetupTriggerTriggeredEvent has been returned for <enum 'EventName'>
2021-11-13 12:38:46 WARNING (MainThread) [pyhoma.enums] Unsupported value SetupTriggerTriggeredEvent has been returned for <enum 'EventName'>
2021-11-13 12:49:46 WARNING (MainThread) [pyhoma.enums] Unsupported value SetupTriggerTriggeredEvent has been returned for <enum 'EventName'>
2021-11-13 12:56:16 WARNING (MainThread) [pyhoma.enums] Unsupported value SetupTriggerTriggeredEvent has been returned for <enum 'EventName'>

**Comment by iMicknl** [comment]
Thanks for confirming, @legantois! We will fix the warnings in an upcoming version of the integration.

**Comment by legantois** [comment]
New version uploaded. most of warnings are gone. Great Job! Thanks a lot on behalf of of all users


new warnings not catched
2021-11-16 08:07:47 WARNING (MainThread) [pyhoma.enums] Unsupported value SomfyProtectCurrentTokenCompletedEvent has been returned for <enum 'EventName'>
2021-11-16 08:10:17 WARNING (MainThread) [pyhoma.enums] Unsupported value GroupTriggeredEvent has been returned for <enum 'EventName'>

My tahoma switch integration supports (firmware from end october 2021 installed- 2021-4-4)
- Velux: open/close + internal curtain using IO homecontrol
- Somfy Double curtain using RTS
- Somfy 3 Rolling curtain using IO homecontrol
- 3 outdoor camera using somfy protect integration

cheers 

Leg
