### ISSUE TITLE
Unable to call execute_command service

### ISSUE THREAD

**Issue by foxdevil13** [iMicknl/ha-tahoma#653]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

I'mt trying to call execute_service from CLI o API, but it does not work. Inside HASS website is working without problem.

For example:
```
$ hass-cli -x service call tahoma.execute_command --arguments command='setControlDHWSettingTemperature',args=[45],entity_id='water_heater.water_element'
/usr/local/lib/python3.7/dist-packages/zeroconf/_services/browser.py:172: FutureWarning: <homeassistant_cli.config._ZeroconfListener object at 0xb5768b50> has no update_service method. Provide one (it can be empty if you don't care about the updates), it'll become mandatory.
  FutureWarning,
Trying to locate Home Assistant on local network...
Found and using http://127.0.0.1:8123 as server
Error calling service: 400 - 400: Bad Request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/homeassistant_cli/cli.py", line 40, in run
    result = cli.main(standalone_mode=False)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/homeassistant_cli/plugins/service.py", line 103, in call
    result = api.call_service(ctx, parts[0], parts[1], data)
  File "/usr/local/lib/python3.7/dist-packages/homeassistant_cli/remote.py", line 574, in call_service
    "Error calling service: {} - {}".format(req.status_code, req.text)
homeassistant_cli.exceptions.HomeAssistantCliError: Error calling service: 400 - 400: Bad Request
```

or using curl with other command:
```
curl -s -X POST -H "Authorization: Bearer xxxxx" http://127.0.0.1:8123/api/services/tahoma/execute_command -d '{"entity_id": "wather_heater.water_element", "command": "setControlDHW", "args": "[run]"
400: Bad Request
```
Any help?

### What version of this integration (ha-tahoma) has the issue?

2.5.0

### What version of Home Assistant Core has the issue?

-

### Which gateway / hub do you use?

Somfy Tahoma

### Device model

-

### Home Assistant log

```shell
Logger: aiohttp.server
Source: custom_components/tahoma/water_heater_devices/hitachi_dhw.py:97
Integration: Overkiz (by Somfy)
First occurred: 3 de noviembre de 2021 13:07:47 (9 occurrences)
Last logged: 16:02:34

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 89, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/api/__init__.py", line 376, in post
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/config/custom_components/tahoma/water_heater_devices/hitachi_dhw.py", line 97, in async_set_operation_mode
    COMMAND_SET_DHW_MODE, OPERATION_MODE_TO_TAHOMA[operation_mode]
KeyError: 'run'
```

**Comment by tetienne** [comment]
Apparently, the command you are trying to run  does not expect any arguments: 

```
{
		"commandName": "refreshDHWMode",
		"nparams": 0
	}
```

**Comment by foxdevil13** [comment]
It doesn't work with any other command, I updated the original post with setControlDHWSettingTemperature command

**Comment by iMicknl** [comment]
Why do you want to run commands via the Home Assistant service via the REST API? I would like to understand your use-case better as well.

Why not directly use the Python API for example?

**Comment by foxdevil13** [comment]
It was my first approach to run it from CLI.

It would be much better to use the Python API, but I could not find any example for running a command only and I'm not very good at Python. Is there any practical example on this?

I would like to control a heating machine with custom made thermostats, mainly on a shell. I was only running HASS to have a platform to run this commands..

**Comment by iMicknl** [comment]
To be honest, your first error via CURL is not related to this integration. And we won't support this either. Perhaps you can ask on the Home Assistant discord or forum. 

The other log error (latest one) looks related to our Home Assist implementation, but it seems that you are not using that?

If you just want a shell, I am not sure if this is the best integration to use. You could have a look at https://github.com/iMicknl/python-tahoma-api or use another Overkiz / TaHoma client. If you need help with the python api, you can always ask on our Discord (see README).
