### ISSUE TITLE
OverkizNumber' object has no attribute '_attr_min_value'

### ISSUE THREAD

**Issue by Mariusthvdb** [iMicknl/ha-tahoma#665]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

see error log

### What version of this integration (ha-tahoma) has the issue?

2.9.3

### What version of Home Assistant Core has the issue?

2022.1.0dev

### Which gateway / hub do you use?

Somfy  Tahoma

### Home Assistant log

```shell
2021-12-07 13:51:38 ERROR (MainThread) [homeassistant.components.number] Error adding entities for domain number with platform tahoma
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 513, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 114, in capability_attributes
    ATTR_MIN: self.min_value,
  File "/config/custom_components/tahoma/number.py", line 82, in min_value
    return self.entity_description.min_value or self._attr_min_value
AttributeError: 'OverkizNumber' object has no attribute '_attr_min_value'
2021-12-07 13:51:38 ERROR (MainThread) [homeassistant.components.number] Error while setting up tahoma platform for number
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 513, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 114, in capability_attributes
    ATTR_MIN: self.min_value,
  File "/config/custom_components/tahoma/number.py", line 82, in min_value
    return self.entity_description.min_value or self._attr_min_value
AttributeError: 'OverkizNumber' object has no attribute '_attr_min_value'
```

**Comment by tetienne** [comment]
Hi,

Thx for reporting this. We will take care of it.

**Comment by iMicknl** [comment]
Fixed in https://github.com/iMicknl/ha-tahoma/pull/667. However, I am not sure when we will release this, since this is only broken in 2022.1.0dev which is not a production version.

We could add extra code to check the environment, but for now, I will just keep the PR open.

**Comment by iMicknl** [comment]
The conflicting change (https://github.com/home-assistant/core/pull/61100) has been merged yesterday, which means it is not in the 2021.12 anymore.

**Comment by Mariusthvdb** [comment]
hmm, using the latest dev still shows:
```
2021-12-08 12:07:59 ERROR (MainThread) [homeassistant.components.number] Error while setting up tahoma platform for number
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 513, in _async_add_entity
capabilities=entity.capability_attributes,
File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 114, in capability_attributes
ATTR_MIN: self.min_value,
File "/config/custom_components/tahoma/number.py", line 82, in min_value
return self.entity_description.min_value or self._attr_min_value
AttributeError: 'OverkizNumber' object has no attribute '_attr_min_value'
```

**Comment by iMicknl** [comment]
What do you mean with latest dev? The latest dev is 2022.1?

**Comment by Mariusthvdb** [comment]
Sorry, I meant dev nightly dev20211208

**Comment by iMicknl** [comment]
Did you use the updated code?

**Comment by Mariusthvdb** [comment]
no, I havent updated, because I am not sure which file to use? do you have a link possibly to the updated integration files?

**Comment by iMicknl** [comment]
If you didn't update, than it won't be fixed for sure 😉. You can use https://github.com/iMicknl/ha-tahoma/archive/refs/heads/fix/665.zip, extract this file and place `custom_components/tahoma` in your `custom_components` folder.

**Comment by Mariusthvdb** [comment]
thanks, and yes, the linked fix/655 fixes it ;-)

**Comment by Mariusthvdb** [comment]
sorry, to nuance the phrase above (no more errors) just letting you know that:
```
2021-12-09 10:10:56 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that accessed discovery_info['hostname'] instead of discovery_info.hostname; this will fail in version 2022.6. Please report issue to the custom component author for tahoma using this method at custom_components/tahoma/config_flow.py, line 129: hostname = discovery_info[HOSTNAME]
```
is still there
