### ISSUE TITLE
Task exception was never retrieved

### ISSUE THREAD

**Issue by kfran78** [iMicknl/ha-tahoma#676]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Since update 2021.12, Overkiz api return a lot of problem. Each action return "IO_FORCE_HEATING_STATE", and i have not a real time refresh (Alarm, cover etc...) 

### What version of this integration (ha-tahoma) has the issue?

V2.10.0

### What version of Home Assistant Core has the issue?

2021.12.1

### Which gateway / hub do you use?

TAHOMA

### Device model

V2/ firmware 2021.5.4

### Home Assistant log

```shell
Cette erreur provient d'une intégration personnalisée

Logger: homeassistant
Source: custom_components/tahoma/switch.py:76
Integration: Overkiz (by Somfy)
First occurred: 09:49:58 (36 occurrences)
Last logged: 10:07:28

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 511, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 935, in state
    return STATE_ON if self.is_on else STATE_OFF
  File "/config/custom_components/tahoma/switch.py", line 76, in is_on
    OverkizState.CORE_ON_OFF, OverkizState.IO_FORCE_HEATING_STATE
  File "/usr/local/lib/python3.9/enum.py", line 429, in __getattr__
    raise AttributeError(name) from None
AttributeError: IO_FORCE_HEATING_STATE
```

### Additional information

it's my first bug report :)

**Comment by tetienne** [comment]
Hi, I fixed with https://github.com/iMicknl/ha-tahoma/issues/677

**Comment by kfran78** [comment]
Correct. Thx.
