### ISSUE TITLE
Error setting up entry mail@example.com for button

### ISSUE THREAD

**Issue by HexomediaVR** [iMicknl/ha-tahoma#684]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Hello,

I updated from 2.9.4 to 2.10.1. I'm facing this error on HA boot.

```
Logger: homeassistant.config_entries
Source: custom_components/tahoma/executor.py:85 
Integration: Overkiz (by Somfy) 
First occurred: 15:18:09 (12 occurrences) 
Last logged: 15:18:09

Error setting up entry mail@example.com for button
Error setting up entry mail@example.com for climate
Error setting up entry mail@example.com for switch
Error setting up entry mail@example.com for water_heater
Error setting up entry mail@example.com for light


Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/binary_sensor/__init__.py", line 163, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_component.py", line 147, in async_setup_entry
    platform = await async_prepare_setup_platform(
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/setup.py", line 309, in async_prepare_setup_platform
    platform = integration.get_platform(domain)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 530, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 535, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/tahoma/binary_sensor.py", line 14, in <module>
    from .entity import OverkizBinarySensorDescription, OverkizDescriptiveEntity
  File "/home/homeassistant/.homeassistant/custom_components/tahoma/entity.py", line 20, in <module>
    from .executor import OverkizExecutor
  File "/home/homeassistant/.homeassistant/custom_components/tahoma/executor.py", line 13, in <module>
    class OverkizExecutor:
  File "/home/homeassistant/.homeassistant/custom_components/tahoma/executor.py", line 85, in OverkizExecutor
    async def async_cancel_command(self, commands_to_cancel: list[str]) -> bool:
TypeError: 'type' object is not subscriptable
```

Thanks. :)

### What version of this integration (ha-tahoma) has the issue?

2.10.1

### What version of Home Assistant Core has the issue?

2021.12.3

### Which gateway / hub do you use?

Somfy TaHoma

### Device model

N/A

**Comment by alexandreaudrain** [comment]
Hi !
Exact same bug for me, with the same configuration.

**Comment by iMicknl** [comment]
Please revert to previous ha-tahoma version and we will have a look. Thanks for reporting.

**Comment by alexandreaudrain** [comment]
Revert back to 2.10.0.
It can’t see any device (only automations).

I’m running HA Core 2021.12.3 with Python 3.8.6.

**Comment by iMicknl** [comment]
Thanks!

Could you give https://github.com/iMicknl/ha-tahoma/archive/refs/heads/fix/684.zip a try? Extract this file and place `custom_components/tahoma` in your `custom_components` folder.

**Comment by alexandreaudrain** [comment]
Hi iMicknl.
I’ll give it a try tomorrow and let you know.
Should I update to latest version before ?

By the way, thanks a lot for all your hard work !

**Comment by alexandreaudrain** [comment]
Hi.
Sorry for the delay : it work like a charm.
Thank you !
