### ISSUE TITLE
Reauth resulted in same account twice

### ISSUE THREAD

**Issue by callifo** [iMicknl/ha-tahoma#687]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

I had the reauth prompt appear a few nights ago, and it did succeed however now I have two accounts with the same username. If I have both enabled, one gets ignored.

This outputs to the log,

2021-12-11 21:13:28 ERROR (MainThread) [homeassistant.components.cover] Platform tahoma does not generate unique IDs. ID rts://x-x-x/x already exists - ignoring cover.master_bedroom
2021-12-11 21:13:28 ERROR (MainThread) [homeassistant.components.cover] Platform tahoma does not generate unique IDs. ID rts://x-x-x/x already exists - ignoring cover.living_room
2021-12-11 21:13:28 ERROR (MainThread) [homeassistant.components.cover] Platform tahoma does not generate unique IDs. ID rts://x-x-x/x already exists - ignoring cover.study
2021-12-11 21:13:28 ERROR (MainThread) [homeassistant.components.cover] Platform tahoma does not generate unique IDs. ID rts://x-x-x/x already exists - ignoring cover.bedroom_3

The second one is listed as 'Not loaded'. I also cannot delete either of them, clicking the hamburger, and then Delete->OK does nothing. Even after a reboot.

### What version of this integration (ha-tahoma) has the issue?

2.10.1

### What version of Home Assistant Core has the issue?

2021.12.3

### Which gateway / hub do you use?

Connexoon Rts Australia

### Device model

Tahoma Basic

### Home Assistant log

```shell
2021-12-11 21:13:28 ERROR (MainThread) [homeassistant.components.cover] Platform tahoma does not generate unique IDs. ID rts://x-x-x/x already exists - ignoring cover.master_bedroom
2021-12-11 21:13:28 ERROR (MainThread) [homeassistant.components.cover] Platform tahoma does not generate unique IDs. ID rts://x-x-x/x already exists - ignoring cover.living_room
2021-12-11 21:13:28 ERROR (MainThread) [homeassistant.components.cover] Platform tahoma does not generate unique IDs. ID rts://x-x-x/x already exists - ignoring cover.study
2021-12-11 21:13:28 ERROR (MainThread) [homeassistant.components.cover] Platform tahoma does not generate unique IDs. ID rts://x-x-x/x already exists - ignoring cover.bedroom_3
```

**Comment by callifo** [comment]
> @callifo please create a new issue for this one. This is not a known bug related to this issue. Could you try to remove the integration from HA entity registrry (integrations page) and than reboot and add again?

If I go to the integration page and try to delete either the disabled one or the currently active one, nothing happens. 

I can try and force uninstall it through HACS; it currently warns me I need to remove the integration through the integration page but I can choose to ignore this error?

**Comment by iMicknl** [comment]
Thanks for reporting, you are currently the only user facing this, thus it is hard to debug for me. I am not sure if we can remove items from the registry manually.

You could try removing it via HACS indeed and reinstall.

**Comment by callifo** [comment]
Unfortunately force uninstalling it does not work, HA now just complains the component has errors during start and I still have two tahoma accounts.

```
2021-12-29 11:47:45 ERROR (MainThread) [homeassistant.setup] Error during setup of component tahoma
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/tahoma/__init__.py", line 78, in setup
    conf = config[DOMAIN]
KeyError: 'tahoma'

```
![image](https://user-images.githubusercontent.com/38901518/147618554-0ff196c2-951e-425d-b43f-b76068c917c1.png)

**Comment by callifo** [comment]
I removed the disabled entry in .storage/core.config_entries which seems to have made it disappear. 

I'll leave it at that for now, if it I get another reauth prompt and it duplicates again, I'll try and delete the remaining entry and remove the integration completely and reinstall.
