### ISSUE TITLE
"'hlrrwifi' is not a valid Protocol" error after last update

### ISSUE THREAD

**Issue by Alex6fr** [iMicknl/ha-tahoma#724]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Hello,

my spx-wfg01 - HitachiAirToAirHeatPump gateway integration stop working after last update.
Integration is Hitachi Hi Kumo (Europe).
Everythink was working before without pb.
Error in log : **ValueError: 'hlrrwifi' is not a valid Protocol**
And : **TypeError: __init__() got an unexpected keyword argument 'min_value'**

Thank's for the help.

### What version of this integration (ha-tahoma) has the issue?

2.12.0

### What version of Home Assistant Core has the issue?

2021.12.10

### Which gateway / hub do you use?

Hitachi Hi Kumo (Europe)

### Device model

spx-wfg01 - HitachiAirToAirHeatPump

### Home Assistant log

<details><summary>Logs</summary>

```
Cette erreur provient d'une intégration personnalisée

Logger: custom_components.tahoma
Source: custom_components/tahoma/__init__.py:64
Integration: Overkiz (by Somfy)
First occurred: 07:55:20 (1 occurrences)
Last logged: 07:55:20

'hlrrwifi' is not a valid Protocol
Traceback (most recent call last):
  File "/config/custom_components/tahoma/__init__.py", line 64, in async_setup_entry
    setup, scenarios = await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.9/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyoverkiz/client.py", line 358, in get_setup
    setup = Setup(**humps.decamelize(response))
  File "/usr/local/lib/python3.9/site-packages/pyoverkiz/models.py", line 63, in __init__
    self.devices = [Device(**d) for d in devices]
  File "/usr/local/lib/python3.9/site-packages/pyoverkiz/models.py", line 63, in <listcomp>
    self.devices = [Device(**d) for d in devices]
  File "/usr/local/lib/python3.9/site-packages/pyoverkiz/models.py", line 185, in __init__
    self.protocol = Protocol(self.device_url.split(":")[0])
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 'hlrrwifi' is not a valid Protocol

```

</details>

### Additional information

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 81, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 147, in async_setup_entry
    platform = await async_prepare_setup_platform(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 309, in async_prepare_setup_platform
    platform = integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/tahoma/number.py", line 22, in <module>
    OverkizNumberDescription(
TypeError: __init__() got an unexpected keyword argument 'min_value'

**Comment by tetienne** [comment]
Hi, sorry for this. I’ve implemented a fix for the protocol issue in our library: https://github.com/iMicknl/python-overkiz-api/pull/341/files

About the min_value, it’s related to a bugfix we merged too soon, it was expected for the next HA release. Meanwhile, you can rollback to the previous version.

**Comment by Alex6fr** [comment]
OK thank's.
It back to work after downgrade to v2.10.2.
I'm waiting the next release ;-)

**Comment by iMicknl** [comment]
Fixed in https://github.com/iMicknl/ha-tahoma/pull/732. We will release a new update soon, or update to latest master.
