### ISSUE TITLE
Failed to setup

### ISSUE THREAD

**Issue by ChengyiP** [iMicknl/ha-tahoma#727]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

I have successfully keyed in the user name and password. However, it shows that it has failed to setup and i m seeing the following error in my home assistant log. Therefore 

```
'rtn' is not a valid Protocol
Traceback (most recent call last):
  File "/config/custom_components/tahoma/__init__.py", line 64, in async_setup_entry
    setup, scenarios = await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.9/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyoverkiz/client.py", line 358, in get_setup
    setup = Setup(**humps.decamelize(response))
  File "/usr/local/lib/python3.9/site-packages/pyoverkiz/models.py", line 63, in __init__
    self.devices = [Device(**d) for d in devices]
  File "/usr/local/lib/python3.9/site-packages/pyoverkiz/models.py", line 63, in <listcomp>
    self.devices = [Device(**d) for d in devices]
  File "/usr/local/lib/python3.9/site-packages/pyoverkiz/models.py", line 185, in __init__
    self.protocol = Protocol(self.device_url.split(":")[0])
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 'rtn' is not a valid Protocol
```

### What version of this integration (ha-tahoma) has the issue?

lastest version

### What version of Home Assistant Core has the issue?

core-2021.12.5

### Which gateway / hub do you use?

Somfy Connexoon

### Device model

unknow.

### Home Assistant log

```
Traceback (most recent call last):
  File "/config/custom_components/tahoma/__init__.py", line 64, in async_setup_entry
    setup, scenarios = await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.9/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyoverkiz/client.py", line 358, in get_setup
    setup = Setup(**humps.decamelize(response))
  File "/usr/local/lib/python3.9/site-packages/pyoverkiz/models.py", line 63, in __init__
    self.devices = [Device(**d) for d in devices]
  File "/usr/local/lib/python3.9/site-packages/pyoverkiz/models.py", line 63, in <listcomp>
    self.devices = [Device(**d) for d in devices]
  File "/usr/local/lib/python3.9/site-packages/pyoverkiz/models.py", line 185, in __init__
    self.protocol = Protocol(self.device_url.split(":")[0])
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 'rtn' is not a valid Protocol
```

**Comment by tetienne** [comment]
Hi, sorry about this. It will be fixed with the next version. 
By curiosity, according to your device, what’s the `rtn` protocol?

**Comment by ChengyiP** [comment]
> Hi, sorry about this. It will be fixed with the next version. By curiosity, according to your device, what’s the `rtn` protocol?

I have no idea what is RTN, i am only aware of it being a RTS somfy blind motor..
