### ISSUE TITLE
Unexpected keyword argument 'min_value'

### ISSUE THREAD

**Issue by animals-uk** [iMicknl/ha-tahoma#728]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Core log shows an "unexpected keyword argument" error on restart, though integration still appears to work

### What version of this integration (ha-tahoma) has the issue?

2.12.0

### What version of Home Assistant Core has the issue?

core-2021.12.10

### Which gateway / hub do you use?

Tahoma

### Device model

Tahoma Pro

### Home Assistant log

<details><summary>Logs</summary>

```
2022-01-26 09:33:04 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Tahoma (~@~.co.uk) for number
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 81, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 147, in async_setup_entry
    platform = await async_prepare_setup_platform(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 309, in async_prepare_setup_platform
    platform = integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/tahoma/number.py", line 22, in <module>
    OverkizNumberDescription(
TypeError: __init__() got an unexpected keyword argument 'min_value'
```

</details>

**Comment by tetienne** [comment]
Hi, we merged a fix too soon, it was expected for the next HA release. You can rollback to the previous version, while we think about a solution.

**Comment by iMicknl** [comment]
Fixed in https://github.com/iMicknl/ha-tahoma/pull/726. We will release a new update soon, or update to latest master.
