### ISSUE TITLE
Implement alternative My button (`goToAlias`)

### ISSUE THREAD

**Issue by Vanntag** [iMicknl/ha-tahoma#738]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Hello.

i have a shutter rts somfy in home assistant via  this integration. I can open/close or stop the shutter. It is seen as a cover. But « my » position is not available.

I see no button to add or else in my device. I only have up down stop controls.

In tahoma application, « my » is available for my shutter. So is it a bug, or a new feature?

### What version of this integration (ha-tahoma) has the issue?

2.12.1

### What version of Home Assistant Core has the issue?

Core-2021-12-10

### Which gateway / hub do you use?

DynamicShutter

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

**Comment by iMicknl** [comment]
Can you add some screenshots of the device page? And please turn on debug mode and add your log here.

If your device supports the 'my' command, a button should be visible.

**Comment by Vanntag** [comment]
![60EDD6F4-F648-440A-AC6F-3B21A9E181D3](https://user-images.githubusercontent.com/94913501/151421288-c0b869e5-4fa9-4612-b46d-ba71d4e91cbb.png)

for the logs, where can I turn them on and also find them?

Thank for your help.

**Comment by Vanntag** [comment]
Attributs for the entity are: 

assumed_state: true
device_class: blind
friendly_name: Volet cuisine
supported_features: 11

**Comment by iMicknl** [comment]
@Vanntag did this ever work for you in ha-tahoma? Your device doesn't have a `my` command, thus we don't add a button. 

**Commands**
[CommandDefinition(command_name='close', nparams=0), 
CommandDefinition(command_name='goToAlias', nparams=1), 
CommandDefinition(command_name='identify', nparams=0),
CommandDefinition(command_name='open', nparams=0), 
CommandDefinition(command_name='saveAlias', nparams=1), 
CommandDefinition(command_name='setName', nparams=1), 
CommandDefinition(command_name='setNodeDefinition', nparams=3),
CommandDefinition(command_name='stop', nparams=0)]),

What you could do is execute the command via tahoma app, and run `tahoma.get_execution_history()` in Home Assistant. Now share your log. (see readme for more details).

**Comment by Vanntag** [comment]
No I have install the integration today, so it s never work. But in tahoma application it’s working.

for the history there is a problem:

`2022-01-27 20:19:16 DEBUG (MainThread) [custom_components.tahoma] Finished fetching device events data in 0.135 seconds (success: True)
2022-01-27 20:19:19 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
2022-01-27 20:19:19 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
2022-01-27 20:19:19 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: '-' is not a valid ExecutionSubType
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 381, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 584, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 733, in admin_handler
    await result
  File "/config/custom_components/tahoma/__init__.py", line 175, in handle_get_execution_history
    await write_execution_history_to_log(coordinator.client)
  File "/config/custom_components/tahoma/__init__.py", line 202, in write_execution_history_to_log
    history = await client.get_execution_history()
  File "/usr/local/lib/python3.9/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyoverkiz/client.py", line 450, in get_execution_history
    execution_history = [HistoryExecution(**h) for h in humps.decamelize(response)]
  File "/usr/local/lib/python3.9/site-packages/pyoverkiz/client.py", line 450, in <listcomp>
    execution_history = [HistoryExecution(**h) for h in humps.decamelize(response)]
  File "/usr/local/lib/python3.9/site-packages/pyoverkiz/models.py", line 612, in __init__
    self.execution_sub_type = ExecutionSubType(execution_sub_type)
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: '-' is not a valid ExecutionSubType
2022-01-27 20:19:19 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [548015218496] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 527, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1260, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 363, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 381, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 584, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 733, in admin_handler
    await result
  File "/config/custom_components/tahoma/__init__.py", line 175, in handle_get_execution_history
    await write_execution_history_to_log(coordinator.client)
  File "/config/custom_components/tahoma/__init__.py", line 202, in write_execution_history_to_log
    history = await client.get_execution_history()
  File "/usr/local/lib/python3.9/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyoverkiz/client.py", line 450, in get_execution_history
    execution_history = [HistoryExecution(**h) for h in humps.decamelize(response)]
  File "/usr/local/lib/python3.9/site-packages/pyoverkiz/client.py", line 450, in <listcomp>
    execution_history = [HistoryExecution(**h) for h in humps.decamelize(response)]
  File "/usr/local/lib/python3.9/site-packages/pyoverkiz/models.py", line 612, in __init__
    self.execution_sub_type = ExecutionSubType(execution_sub_type)
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: '-' is not a valid ExecutionSubType `

**Comment by iMicknl** [comment]
Sorry, I edited my previous message just before you replied.

> It seems that your device is quite special and I am not sure if we can support this on short-term. Do you use this feature a lot?

>What if you press the stop button, will that do the same?

**Comment by Vanntag** [comment]
Yes I use it a lot, every day. If i press stop button, it just stop. And if I press again, nothing happen. So it’s a new feature? So I have to create a new feature request? I understand if you don’t implement it tomorrow :-)

**Comment by tetienne** [comment]
@Vanntag Sorry to jump in this topic, but I see you are using an hub we didn’t know. Can you please restart HA, and look for a log: `'xxxx' is not a valid Gateway`? I will add it to our list.

About your question, we already support My feature, but your case is not usual, so we have to understand how it works.

**Comment by Vanntag** [comment]
@tetienne I restart HA, but all I've found is:
`2022-01-27 21:25:58 WARNING (MainThread) [pyoverkiz.enums.gateway] Unsupported value 99 has been returned for <enum 'GatewayType'>`

Is it what you are looking for?

Or otherwise I have this:
`2022-01-27 21:25:59 DEBUG (MainThread) [custom_components.tahoma] Added gateway (Gateway(partners=[], functions='', sub_type=<GatewaySubType.TAHOMA_BASIC_PLUS: 2>, id=****-****-1038, gateway_id=****-****-1038, alive=True, mode='ACTIVE', place_oid='622cb1d9-046d-4124-97f2-3fd9d1b105cf', time_reliable=True, connectivity=Connectivity(status='OK', protocol_version='1'), up_to_date=True, update_status=<UpdateBoxStatus.UP_TO_DATE: 'UP_TO_DATE'>, sync_in_progress=False, type=<GatewayType.UNKNOWN: -1>))`

But that 's all.

**Comment by tetienne** [comment]
@Vanntag Thx it’s well what I was looking for.

**Comment by tetienne** [comment]
@Vanntag Which gateway / hub do you use?

**Comment by Vanntag** [comment]
I’m using the new « kit de connexion » from Somfy. It only have rts and io protocols.

**Comment by Vanntag** [comment]
I just realize where maybe the problem came from. My shutter is from the brand « simu ». They are using rts protocol from somfy. Maybe this is why « my » is not enable? Even if it is in tahoma application.
I hope it will help you. Thanks again for your help and your time.

**Comment by iMicknl** [comment]
@Vanntag we need to implement this in a different way, and will do in the coming weeks! Currently active development is paused until we port everything from core, but we at least know where to look now.

```
CommandDefinition(command_name='goToAlias', nparams=1)
```

```
State(name='core:SupportedAliases', type=<DataType.JSON_ARRAY: 10>, value=[{'id': '1', 'type': 'favorite1', 'features': ['openClose']}])
```

**Comment by iMicknl** [comment]
@Vanntag this is now merged into core and will hopefully ship this or next version.
