### ISSUE TITLE
__init__() missing 2 required keyword-only arguments: 'widget' and 'ui_class'

### ISSUE THREAD

**Issue by jensihnow** [iMicknl/ha-tahoma#742]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Hi,

I believe I have a similar issue like this one https://github.com/iMicknl/ha-tahoma/issues/367. While running the Integration using HACS it stopped at some point and I thought about the log-in issue being the case. After these fixes, I actually never got it working again. When I delete the Integration it will be discovered.

Actually multiple times, no idea why:

<details><summary>Multi Discovery</summary>

```
2022-02-01 09:36:38 DEBUG (MainThread) [custom_components.tahoma.config_flow] ZeroConf discovery detected gateway ****-****-2554
2022-02-01 09:36:38 DEBUG (MainThread) [custom_components.tahoma.config_flow] ZeroConf discovery detected gateway ****-****-2554
2022-02-01 09:36:59 DEBUG (MainThread) [custom_components.tahoma.config_flow] DHCP discovery detected gateway ****-****-2554
```
</details>

Anyways, I can start the setup/config dialog. After submitting the credentials everything seems to be fine, but it immediately switches to error. I have the feeling I'm not getting past the config e.g., getSetup. I also wonder if this is related to some (old) Z-Wave device still being available (can't delete it using the Somfy UI). The only output I get is the TypeError attached.

### What version of this integration (ha-tahoma) has the issue?

2.12.1

### What version of Home Assistant Core has the issue?

2021.12.10

### Which gateway / hub do you use?

Somfy TaHoma Box 

### Home Assistant log

<details><summary>Logs</summary>

```
2022-02-01 09:30:10 ERROR (MainThread) [custom_components.tahoma] __init__() missing 2 required keyword-only arguments: 'widget' and 'ui_class'
Traceback (most recent call last):
  File "/config/custom_components/tahoma/__init__.py", line 69, in async_setup_entry
    setup, scenarios = await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.9/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyoverkiz/client.py", line 362, in get_setup
    setup = Setup(**humps.decamelize(response))
  File "/usr/local/lib/python3.9/site-packages/pyoverkiz/models.py", line 63, in __init__
    self.devices = [Device(**d) for d in devices]
  File "/usr/local/lib/python3.9/site-packages/pyoverkiz/models.py", line 63, in <listcomp>
    self.devices = [Device(**d) for d in devices]
TypeError: __init__() missing 2 required keyword-only arguments: 'widget' and 'ui_class'
```
</details>

**Comment by jensihnow** [comment]
Got it back working with v2.10.1 and could pull some logging data for unsupported devices:

<details><summary>Log</summary>

```
2022-02-01 22:31:36 DEBUG (MainThread) [custom_components.tahoma] Unsupported device detected (Device(attributes=States(_states=[]), available=False, enabled=True, label='ZWAVE (2#1)', device_url=zwave://****-****-xxxx/2#1, controllable_name='zwave:ZWaveOccupancySensor', definition=Definition(commands=CommandDefinitions(_commands=[]), states=[], widget_name=None, ui_class=None, qualified_name='zwave:ZWaveOccupancySensor'), data_properties=None, widget=None, ui_class=None, states=States(_states=[]), type=<ProductType.NONE: 0>, place_oid='xxx'))
2022-02-01 22:31:36 DEBUG (MainThread) [custom_components.tahoma] Unsupported device detected (Device(attributes=States(_states=[State(name='core:MeasuredValueType', type=<DataType.STRING: 3>, value='core:TemperatureInCelcius')]), available=False, enabled=True, label='ZWAVE (2#2)', device_url=zwave://****-****-xxxx/2#2, controllable_name='zwave:ZWaveTemperatureSensor', definition=Definition(commands=CommandDefinitions(_commands=[CommandDefinition(command_name='refreshTemperature', nparams=0)]), states=[StateDefinition(qualified_name='core:DeviceDefectState', type='DiscreteState', values=['failed']), StateDefinition(qualified_name='core:NeighboursAddressesState', type='DataState', values=None), StateDefinition(qualified_name='core:TemperatureState', type='ContinuousState', values=None)], widget_name='TemperatureSensor', ui_class='TemperatureSensor', qualified_name='zwave:ZWaveTemperatureSensor'), data_properties=None, widget='TemperatureSensor', ui_class='TemperatureSensor', states=States(_states=[]), type=<ProductType.SENSOR: 2>, place_oid='xxx'))
2022-02-01 22:31:36 DEBUG (MainThread) [custom_components.tahoma] Unsupported device detected (Device(attributes=States(_states=[State(name='core:MeasuredValueType', type=<DataType.STRING: 3>, value='core:LuminanceInLux')]), available=False, enabled=True, label='ZWAVE (2#3)', device_url=zwave://****-****-xxxx/2#3, controllable_name='zwave:ZWaveLightSensor', definition=Definition(commands=CommandDefinitions(_commands=[]), states=[StateDefinition(qualified_name='core:DeviceDefectState', type='DiscreteState', values=['failed']), StateDefinition(qualified_name='core:LuminanceState', type='ContinuousState', values=None), StateDefinition(qualified_name='core:NeighboursAddressesState', type='DataState', values=None)], widget_name='LuminanceSensor', ui_class='LightSensor', qualified_name='zwave:ZWaveLightSensor'), data_properties=None, widget='LuminanceSensor', ui_class='LightSensor', states=States(_states=[]), type=<ProductType.SENSOR: 2>, place_oid='xxx'))

```
</details>

**Comment by tetienne** [comment]
It’s curious, as we didn’t change code related to how we load the device. In your last logs, I can indeed see `widget=None, ui_class=None`, but I don’t see how we can return this. 
May I ask you to retry with the v2.10.2 to see if it’s really linked to this version?

**Comment by jensihnow** [comment]
Updated to v2.10.2 using HACS re-download and restarted HA, and it worked. Next I tried v2.11.0 and this gave me the exception again. So change is between v2.10.2 (working) and v2.11.0 (not working). This seems to reduce to scope to a few PRs, unfortunately one is rather big (#690).

**Comment by iMicknl** [comment]
It is related to us pulling in `get_setup()` instead of the separate calls. However, we need to double check since widget and ui class should never be none...

Can you message me [via Discord](https://discord.gg/gDSNf8MKf7) (iMick #1903) so we can speed up the development? Easiest would be if you could temporary change your password and send your credentials, so I can do some live debugging on my machine.

I have some feeling that Somfy messes up, or that we incorrectly think that widget and ui_class is a mandatory value.

**Comment by iMicknl** [comment]
By the way, you probably will have the same issue with the Overkiz integration in core (which has been released yesterday).

**Comment by iMicknl** [comment]
```
{
    "creationTime": 1472213846000,
    "lastUpdateTime": 1472213846000,
    "label": "ZWAVE (2#1)",
    "deviceURL": "zwave://1202-1763-2554/2#1",
    "shortcut": false,
    "controllableName": "zwave:ZWaveOccupancySensor",
    "definition": {
        "commands": [],
        "states": [],
        "dataProperties": [],
        "qualifiedName": "zwave:ZWaveOccupancySensor",
        "type": "UNKNOWN"
    },
    "available": false,
    "enabled": true,
    "placeOID": "4028839f3021fe260130cdbc5f5757b4",
    "type": 0,
    "oid": "073e82c4-f8cb-4849-9269-4b440ef32efb"
}
```

Apparently there was a (partial) device in your setup.json which was added 5 years ago. I guess you spotted a bug on Somfy / Overkiz side, but could be related to your box migration / partial removal perhaps. However, it has been fixed now after manually removing the device via API. Posting this here for reference.

**Comment by iMicknl** [comment]
@tetienne looking at https://github.com/iMicknl/ha-tahoma/issues/205 and https://github.com/iMicknl/ha-tahoma/issues/99, we maybe need to check if we still mark them as optional (or if we can make them required again).

**Comment by tetienne** [comment]
Well if they can be missing we have to mark them as optional. But it means also update the code to check if or not the value is present. It should be OK

**Comment by iMicknl** [comment]
> Well if they can be missing we have to mark them as optional. But it means also update the code to check if or not the value is present. It should be OK

I don't think they can be missing. This was a 5 year old device that was just partially there, seems more a bug than a feature.

**Comment by jensihnow** [comment]
Thanks @iMicknl for debugging and helping to resolve this one! Much appreciated.
