### ISSUE TITLE
__init__() missing 2 required keyword-only arguments: 'device_url' and 'place_oid'

### ISSUE THREAD

**Issue by BjornTheKing** [iMicknl/ha-tahoma#792]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Hi

I tried to upgade to the latest version (2.13.0) and I get errors. I was running an old version from 2021 before this (not sure howto check version). I dont't know what I am doing wrong :)

regards
/Bjorn

Logger: custom_components.tahoma
Source: custom_components/tahoma/__init__.py:86
Integration: Overkiz (by Somfy) - Custom component
First occurred: 11:35:28 AM (1 occurrences)
Last logged: 11:35:28 AM

__init__() missing 2 required keyword-only arguments: 'device_url' and 'place_oid'
Traceback (most recent call last):
  File "/config/custom_components/tahoma/__init__.py", line 86, in async_setup_entry
    setup, scenarios = await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.9/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyoverkiz/client.py", line 368, in get_setup
    setup = Setup(**humps.decamelize(response))
  File "/usr/local/lib/python3.9/site-packages/pyoverkiz/models.py", line 63, in __init__
    self.devices = [Device(**d) for d in devices]
  File "/usr/local/lib/python3.9/site-packages/pyoverkiz/models.py", line 63, in <listcomp>
    self.devices = [Device(**d) for d in devices]
TypeError: __init__() missing 2 required keyword-only arguments: 'device_url' and 'place_oid'

### What version of this integration (ha-tahoma) has the issue?

2.13.0

### What version of Home Assistant Core has the issue?

core-2022.3.5

### Which gateway / hub do you use?

Somfy Connexoon RTS

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks. The first log line must start with "Added device (Device...".
```

</details>

**Comment by tetienne** [comment]
Hi, this should be easy to fix. But that's the first time I saw this issue. Without device url, the device is pretty useless as we cannot call it.

What kind of device have you?

**Comment by BjornTheKing** [comment]
I have a connexoon-device from Somfy. I guess they refer to it as Connexoon RTS or something when I look around on google. I had it installed 1.5 years ago for controlling an awning (sun blind).
On the back side label it says
Connexoon 
1811429 A
Somfy F-74300 CLUSES

**Comment by iMicknl** [comment]
Could it be that you still have an old / broken device in your config? The only time I have seen this, there was an old z-wave device in their config, which we needed to remove manually.

**Comment by BjornTheKing** [comment]
Not sure. I am not really that good at many things in HASS, but I am learning :)

I have added this manually in custom_components and when I use a bit older version I had (not sure how to check version) it works and with the latest it does not (I delete the integration.... replace the tahoma folders with the version I want to run ... restart ... and add the integration again).
How do I check if I have some old or broken device in my config? Looking on the configurations/devices page it looks like all devices are OK.

**Comment by iMicknl** [comment]
In the official vendor app, does another device show up? I would love to gather your diagnostic data, however I am not able to get that if this error shows up :(.

Would you be able to work with me [via Discord](https://discord.gg/RRXuSVDAzG) (iMick #1903) so we can speed up the development? Easiest would be if you could temporary change your password and send your credentials, so I can do some live debugging on my machine.

**Comment by BjornTheKing** [comment]
I'm running something called connexoon terrace app on my phone and it is nothing strange there. I cannot run the tahoma app since it says that I should use the app I am using.

My credentials on Somfy you mean?

**Comment by iMicknl** [comment]
It works here without issues on latest core. Let's see where the culprit could be. Posting your diagnostics information for reference.

```json
{
	"device": {
		"controllable_name": null,
		"firmware": "2022.1.4",
		"device_url": "****-****-7622",
		"model": "Somfy Box"
	},
	"setup": {
		"creationTime": 1601913406000,
		"lastUpdateTime": 1601913406000,
		"id": "SETUP-****-****-7622",
		"location": {
			"creationTime": 1601913406000,
			"lastUpdateTime": 1601931779000,
			"city": "**\u00e4** **\u00f6**",
			"country": "**",
			"postalCode": "** **",
			"addressLine1": "**\u00e5** **",
			"addressLine2": "*",
			"timezone": "Europe/Stockholm",
			"longitude": "**",
			"latitude": "**",
			"twilightMode": 2,
			"twilightAngle": "CIVIL",
			"twilightCity": "stockholm",
			"summerSolsticeDuskMinutes": 1290,
			"winterSolsticeDuskMinutes": 990,
			"twilightOffsetEnabled": false,
			"dawnOffset": 0,
			"duskOffset": 0,
			"countryCode": "SE"
		},
		"gateways": [{
			"gatewayId": "****-****-7622",
			"type": 34,
			"subType": 4,
			"placeOID": "60b7283d-51b0-4843-9388-2f6022095fc2",
			"alive": true,
			"timeReliable": true,
			"connectivity": {
				"status": "OK",
				"protocolVersion": "2022.1.4"
			},
			"upToDate": true,
			"updateStatus": "UP_TO_DATE",
			"syncInProgress": false,
			"mode": "ACTIVE",
			"functions": "INTERNET_AUTHORIZATION,SCENARIO_DOWNLOAD,SCENARIO_AUTO_LAUNCHING,SCENARIO_TELECO_LAUNCHING,INTERNET_UPLOAD,INTERNET_UPDATE,TRIGGERS_SENSORS"
		}],
		"devices": [{
				"creationTime": 1601913406000,
				"lastUpdateTime": 1601913406000,
				"label": "**",
				"deviceURL": "internal://****-****-7622/pod/0",
				"shortcut": false,
				"controllableName": "internal:PodMiniComponent",
				"definition": {
					"commands": [{
							"commandName": "getName",
							"nparams": 0
						},
						{
							"commandName": "update",
							"nparams": 0
						},
						{
							"commandName": "setCountryCode",
							"nparams": 1
						},
						{
							"commandName": "activateCalendar",
							"nparams": 0
						},
						{
							"commandName": "deactivateCalendar",
							"nparams": 0
						},
						{
							"commandName": "refreshPodMode",
							"nparams": 0
						},
						{
							"commandName": "refreshUpdateStatus",
							"nparams": 0
						},
						{
							"commandName": "setCalendar",
							"nparams": 1
						},
						{
							"commandName": "setLightingLedPodMode",
							"nparams": 1
						},
						{
							"commandName": "setPodLedOff",
							"nparams": 0
						},
						{
							"commandName": "setPodLedOn",
							"nparams": 0
						}
					],
					"states": [{
							"type": "DiscreteState",
							"values": [
								"offline",
								"online"
							],
							"qualifiedName": "core:ConnectivityState"
						},
						{
							"type": "DataState",
							"qualifiedName": "core:CountryCodeState"
						},
						{
							"type": "DataState",
							"qualifiedName": "core:LocalIPv4AddressState"
						},
						{
							"type": "DataState",
							"qualifiedName": "core:NameState"
						},
						{
							"type": "DiscreteState",
							"values": [
								"doublePress",
								"longPress",
								"simplePress",
								"triplePress",
								"veryLongPress"
							],
							"qualifiedName": "internal:LastActionConfigButtonState"
						},
						{
							"type": "ContinuousState",
							"qualifiedName": "internal:LightingLedPodModeState"
						}
					],
					"dataProperties": [],
					"widgetName": "Pod",
					"uiProfiles": [
						"UpdatableComponent"
					],
					"uiClass": "Pod",
					"qualifiedName": "internal:PodMiniComponent",
					"type": "ACTUATOR"
				},
				"states": [{
						"name": "internal:LightingLedPodModeState",
						"type": 2,
						"value": 1.0
					},
					{
						"name": "core:CountryCodeState",
						"type": 3,
						"value": "SE"
					},
					{
						"name": "core:LocalIPv4AddressState",
						"type": 3,
						"value": "N/A"
					},
					{
						"name": "core:NameState",
						"type": 3,
						"value": "**"
					}
				],
				"available": true,
				"enabled": true,
				"placeOID": "60b7283d-51b0-4843-9388-2f6022095fc2",
				"widget": "Pod",
				"type": 1,
				"oid": "976bbff0-4dd9-4fa6-b38b-df256211aca3",
				"uiClass": "Pod"
			},
			{
				"creationTime": 1601925736000,
				"lastUpdateTime": 1601925736000,
				"label": "** **",
				"deviceURL": "io://****-****-7622/10519950",
				"shortcut": false,
				"controllableName": "io:HorizontalAwningIOComponent",
				"definition": {
					"commands": [{
							"commandName": "advancedRefresh",
							"nparams": 1
						},
						{
							"commandName": "close",
							"nparams": 0
						},
						{
							"commandName": "delayedStopIdentify",
							"nparams": 1
						},
						{
							"commandName": "deploy",
							"nparams": 0
						},
						{
							"commandName": "down",
							"nparams": 0
						},
						{
							"commandName": "getName",
							"nparams": 0
						},
						{
							"commandName": "identify",
							"nparams": 0
						},
						{
							"commandName": "my",
							"nparams": 0
						},
						{
							"commandName": "open",
							"nparams": 0
						},
						{
							"commandName": "refreshMemorized1Position",
							"nparams": 0
						},
						{
							"commandName": "setClosure",
							"nparams": 1
						},
						{
							"commandName": "setDeployment",
							"nparams": 1
						},
						{
							"commandName": "setMemorized1Position",
							"nparams": 1
						},
						{
							"commandName": "setName",
							"nparams": 1
						},
						{
							"commandName": "setPosition",
							"nparams": 1
						},
						{
							"commandName": "setSecuredPosition",
							"nparams": 1
						},
						{
							"commandName": "startIdentify",
							"nparams": 0
						},
						{
							"commandName": "stop",
							"nparams": 0
						},
						{
							"commandName": "stopIdentify",
							"nparams": 0
						},
						{
							"commandName": "undeploy",
							"nparams": 0
						},
						{
							"commandName": "up",
							"nparams": 0
						},
						{
							"commandName": "wink",
							"nparams": 1
						},
						{
							"commandName": "runManufacturerSettingsCommand",
							"nparams": 2
						},
						{
							"commandName": "keepOneWayControllersAndDeleteNode",
							"nparams": 0
						},
						{
							"commandName": "pairOneWayController",
							"nparams": 2
						},
						{
							"commandName": "sendIOKey",
							"nparams": 0
						},
						{
							"commandName": "setConfigState",
							"nparams": 1
						},
						{
							"commandName": "unpairAllOneWayControllersAndDeleteNode",
							"nparams": 0
						},
						{
							"commandName": "unpairAllOneWayControllers",
							"nparams": 0
						},
						{
							"commandName": "unpairOneWayController",
							"nparams": 2
						}
					],
					"states": [{
							"type": "DataState",
							"qualifiedName": "core:AdditionalStatusState"
						},
						{
							"type": "ContinuousState",
							"qualifiedName": "core:DeploymentState"
						},
						{
							"type": "DiscreteState",
							"values": [
								"good",
								"low",
								"normal",
								"verylow"
							],
							"qualifiedName": "core:DiscreteRSSILevelState"
						},
						{
							"type": "DataState",
							"qualifiedName": "core:ManufacturerSettingsState"
						},
						{
							"type": "ContinuousState",
							"qualifiedName": "core:Memorized1PositionState"
						},
						{
							"type": "DiscreteState",
							"values": [
								"false",
								"true"
							],
							"qualifiedName": "core:MovingState"
						},
						{
							"type": "DataState",
							"qualifiedName": "core:NameState"
						},
						{
							"type": "DiscreteState",
							"values": [
								"closed",
								"open"
							],
							"qualifiedName": "core:OpenClosedState"
						},
						{
							"type": "ContinuousState",
							"qualifiedName": "core:PriorityLockTimerState"
						},
						{
							"type": "ContinuousState",
							"qualifiedName": "core:RSSILevelState"
						},
						{
							"type": "ContinuousState",
							"qualifiedName": "core:SecuredPositionState"
						},
						{
							"type": "DiscreteState",
							"values": [
								"available",
								"unavailable"
							],
							"qualifiedName": "core:StatusState"
						},
						{
							"type": "ContinuousState",
							"qualifiedName": "core:TargetClosureState"
						},
						{
							"type": "DiscreteState",
							"values": [
								"comfortLevel1",
								"comfortLevel2",
								"comfortLevel3",
								"comfortLevel4",
								"environmentProtection",
								"humanProtection",
								"userLevel1",
								"userLevel2"
							],
							"qualifiedName": "io:PriorityLockLevelState"
						},
						{
							"type": "DiscreteState",
							"values": [
								"LSC",
								"SAAC",
								"SFC",
								"UPS",
								"externalGateway",
								"localUser",
								"myself",
								"rain",
								"security",
								"temperature",
								"timer",
								"user",
								"wind"
							],
							"qualifiedName": "io:PriorityLockOriginatorState"
						}
					],
					"dataProperties": [{
						"value": "500",
						"qualifiedName": "core:identifyInterval"
					}],
					"widgetName": "PositionableHorizontalAwning",
					"uiProfiles": [
						"StatefulDeployableAwning",
						"StatefulDeployable",
						"Deployable",
						"DeployUndeploy",
						"StatefulOpenClose",
						"OpenClose"
					],
					"uiClass": "Awning",
					"qualifiedName": "io:HorizontalAwningIOComponent",
					"type": "ACTUATOR"
				},
				"states": [{
						"name": "core:NameState",
						"type": 3,
						"value": "** **"
					},
					{
						"name": "core:PriorityLockTimerState",
						"type": 1,
						"value": 0
					},
					{
						"name": "core:StatusState",
						"type": 3,
						"value": "available"
					},
					{
						"name": "core:DiscreteRSSILevelState",
						"type": 3,
						"value": "normal"
					},
					{
						"name": "core:RSSILevelState",
						"type": 2,
						"value": 78.0
					},
					{
						"name": "core:OpenClosedState",
						"type": 3,
						"value": "closed"
					},
					{
						"name": "core:DeploymentState",
						"type": 1,
						"value": 0
					},
					{
						"name": "core:Memorized1PositionState",
						"type": 1,
						"value": 105
					},
					{
						"name": "core:TargetClosureState",
						"type": 1,
						"value": 0
					},
					{
						"name": "core:MovingState",
						"type": 6,
						"value": false
					}
				],
				"attributes": [{
						"name": "core:SupportedManufacturerSettingsCommands",
						"type": 10,
						"value": [
							"dead_man_up",
							"dead_man_down",
							"dead_man_stop",
							"dead_man_impulse_up",
							"dead_man_impulse_down",
							"enter_settings_mode",
							"save_upper_end_limit",
							"save_lower_end_limit",
							"stop_after_save_limit",
							"save_settings",
							"invert_rotation",
							"save_my_position",
							"delete_my_position",
							"reset_actuator",
							"double_power_cut",
							"eject_from_setting_mode",
							"enter_back_impulse_setting_mode",
							"save_back_impulse_position"
						]
					},
					{
						"name": "core:FirmwareRevision",
						"type": 3,
						"value": "5104761X04"
					},
					{
						"name": "core:Manufacturer",
						"type": 3,
						"value": "Somfy"
					}
				],
				"available": true,
				"enabled": true,
				"placeOID": "60b7283d-51b0-4843-9388-2f6022095fc2",
				"widget": "PositionableHorizontalAwning",
				"type": 1,
				"oid": "02d729ef-60f1-42a5-a06b-07ae220efcc0",
				"uiClass": "Awning"
			},
			{
				"creationTime": 1601915138000,
				"lastUpdateTime": 1601915138000,
				"label": "** *(**)*",
				"deviceURL": "io://****-****-7622/3466037",
				"shortcut": false,
				"controllableName": "io:StackComponent",
				"definition": {
					"commands": [{
							"commandName": "advancedSomfyDiscover",
							"nparams": 1
						},
						{
							"commandName": "discover1WayController",
							"nparams": 2
						},
						{
							"commandName": "discoverActuators",
							"nparams": 1
						},
						{
							"commandName": "discoverSensors",
							"nparams": 1
						},
						{
							"commandName": "discoverSomfyUnsetActuators",
							"nparams": 0
						},
						{
							"commandName": "joinNetwork",
							"nparams": 0
						},
						{
							"commandName": "resetNetworkSecurity",
							"nparams": 0
						},
						{
							"commandName": "shareNetwork",
							"nparams": 0
						}
					],
					"states": [],
					"dataProperties": [],
					"widgetName": "IOStack",
					"uiProfiles": [
						"Specific"
					],
					"uiClass": "ProtocolGateway",
					"qualifiedName": "io:StackComponent",
					"type": "PROTOCOL_GATEWAY"
				},
				"available": true,
				"enabled": true,
				"placeOID": "60b7283d-51b0-4843-9388-2f6022095fc2",
				"widget": "IOStack",
				"type": 5,
				"oid": "ddda3b24-7cff-4d4f-b2b7-550ef42a8bfb",
				"uiClass": "ProtocolGateway"
			},
			{
				"creationTime": 1601913406000,
				"lastUpdateTime": 1601913406000,
				"label": "** *(**)*",
				"deviceURL": "ogp://****-****-7622/00000BE8",
				"shortcut": false,
				"controllableName": "ogp:Bridge",
				"definition": {
					"commands": [{
						"commandName": "sendPrivate",
						"nparams": 1
					}],
					"states": [{
							"type": "DataState",
							"qualifiedName": "core:Private10State"
						},
						{
							"type": "DataState",
							"qualifiedName": "core:Private1State"
						},
						{
							"type": "DataState",
							"qualifiedName": "core:Private2State"
						},
						{
							"type": "DataState",
							"qualifiedName": "core:Private3State"
						},
						{
							"type": "DataState",
							"qualifiedName": "core:Private4State"
						},
						{
							"type": "DataState",
							"qualifiedName": "core:Private5State"
						},
						{
							"type": "DataState",
							"qualifiedName": "core:Private6State"
						},
						{
							"type": "DataState",
							"qualifiedName": "core:Private7State"
						},
						{
							"type": "DataState",
							"qualifiedName": "core:Private8State"
						},
						{
							"type": "DataState",
							"qualifiedName": "core:Private9State"
						}
					],
					"dataProperties": [],
					"widgetName": "DynamicBridge",
					"uiProfiles": [
						"Specific"
					],
					"uiClass": "ProtocolGateway",
					"qualifiedName": "ogp:Bridge",
					"type": "ACTUATOR"
				},
				"attributes": [{
					"name": "ogp:Features",
					"type": 10,
					"value": [{
						"name": "private"
					}]
				}],
				"available": true,
				"enabled": true,
				"placeOID": "60b7283d-51b0-4843-9388-2f6022095fc2",
				"widget": "DynamicBridge",
				"type": 1,
				"oid": "7e159bc5-1c88-4cce-9d6f-4de9dca0aad0",
				"uiClass": "ProtocolGateway"
			},
			{
				"creationTime": 1601913406000,
				"lastUpdateTime": 1601913406000,
				"label": "** ** **",
				"deviceURL": "ogp://****-****-7622/039575E9",
				"shortcut": false,
				"controllableName": "ogp:Bridge",
				"definition": {
					"commands": [{
							"commandName": "discover",
							"nparams": 0
						},
						{
							"commandName": "identify",
							"nparams": 0
						},
						{
							"commandName": "setName",
							"nparams": 1
						}
					],
					"states": [{
							"type": "DiscreteState",
							"values": [
								"available",
								"unavailable"
							],
							"qualifiedName": "core:AvailabilityState"
						},
						{
							"type": "DataState",
							"qualifiedName": "core:NameState"
						},
						{
							"type": "DataState",
							"qualifiedName": "core:RemovableState"
						}
					],
					"dataProperties": [],
					"widgetName": "DynamicBridge",
					"uiProfiles": [
						"Specific"
					],
					"uiClass": "ProtocolGateway",
					"qualifiedName": "ogp:Bridge",
					"type": "ACTUATOR"
				},
				"states": [{
					"name": "core:NameState",
					"type": 3,
					"value": "** ** **"
				}],
				"attributes": [{
						"name": "core:Manufacturer",
						"type": 3,
						"value": "Overkiz"
					},
					{
						"name": "ogp:Features",
						"type": 10,
						"value": [{
								"name": "discovery"
							},
							{
								"name": "identification"
							}
						]
					},
					{
						"name": "core:Technology",
						"type": 3,
						"value": "Siegenia"
					},
					{
						"name": "core:ManufacturerReference",
						"type": 3,
						"value": "OGP Siegenia Bridge"
					}
				],
				"available": true,
				"enabled": true,
				"placeOID": "60b7283d-51b0-4843-9388-2f6022095fc2",
				"widget": "DynamicBridge",
				"type": 1,
				"oid": "5098a065-97b1-451e-93d5-e39bdd16e2a4",
				"uiClass": "ProtocolGateway"
			},
			{
				"creationTime": 1601913406000,
				"lastUpdateTime": 1601913406000,
				"label": "** ** **",
				"deviceURL": "ogp://****-****-7622/09E45393",
				"shortcut": false,
				"controllableName": "ogp:Bridge",
				"definition": {
					"commands": [{
							"commandName": "discover",
							"nparams": 0
						},
						{
							"commandName": "identify",
							"nparams": 0
						},
						{
							"commandName": "setName",
							"nparams": 1
						}
					],
					"states": [{
							"type": "DiscreteState",
							"values": [
								"available",
								"unavailable"
							],
							"qualifiedName": "core:AvailabilityState"
						},
						{
							"type": "DataState",
							"qualifiedName": "core:NameState"
						},
						{
							"type": "DataState",
							"qualifiedName": "core:RemovableState"
						}
					],
					"dataProperties": [],
					"widgetName": "DynamicBridge",
					"uiProfiles": [
						"Specific"
					],
					"uiClass": "ProtocolGateway",
					"qualifiedName": "ogp:Bridge",
					"type": "ACTUATOR"
				},
				"states": [{
					"name": "core:NameState",
					"type": 3,
					"value": "** ** **"
				}],
				"attributes": [{
						"name": "core:ManufacturerReference",
						"type": 3,
						"value": "OGP Intesis Bridge"
					},
					{
						"name": "core:Manufacturer",
						"type": 3,
						"value": "Overkiz"
					},
					{
						"name": "ogp:Features",
						"type": 10,
						"value": [{
								"name": "discovery"
							},
							{
								"name": "identification"
							}
						]
					},
					{
						"name": "core:Technology",
						"type": 3,
						"value": "Intesis"
					}
				],
				"available": true,
				"enabled": true,
				"placeOID": "60b7283d-51b0-4843-9388-2f6022095fc2",
				"widget": "DynamicBridge",
				"type": 1,
				"oid": "a19a37a9-3877-4b53-b5fe-f80cad08e34f",
				"uiClass": "ProtocolGateway"
			}
		],
		"zones": [],
		"resellerDelegationType": "NEVER",
		"oid": "df0ba419-04a0-4aae-8e2e-00d25a4727b3",
		"rootPlace": {
			"creationTime": 1601913406000,
			"lastUpdateTime": 1601913406000,
			"label": "** **",
			"type": 0,
			"oid": "60b7283d-51b0-4843-9388-2f6022095fc2",
			"subPlaces": []
		},
		"features": [{
				"name": "connexoon-terrace",
				"source": "GATEWAY_TYPE"
			},
			{
				"name": "connexoon-access",
				"source": "LOCAL_OPTION"
			}
		]
	},
	"server": "somfy_europe",
	"execution_history": []
}
```
