### ISSUE TITLE
Wrong behavior with AtlanticElectricalHeaterWithAdjustableTemperatureSetpoint and eco temperature

### ISSUE THREAD

**Issue by spanska** [iMicknl/ha-tahoma#839]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Duplicate of https://github.com/home-assistant/core/issues/86322

The Atlantic Heater eco temperature setter is design to take the number of degrees bellow the comfort temperature and not an absolute value despite what is shown on the Atlantic Cozytouch App.

ie :

if comfort tempature is set to 17.5°C
we need to send 2.5 to eco temperature endpoint to set eco temperature to 15°C
currently, the overkiz integration doesn't work that way and try to set an absolute value between 6 and 29 to the eco temperature endpoint. Furthemore, the eco temperature getter is also false as shown bellow :

![image](https://user-images.githubusercontent.com/17727967/215454572-390f6ebe-8146-4b67-bf32-6603d9f7aa99.png)

For your information, the eco temperature is set to 15°C in this case in the cozytouch app.

### What version of this integration (ha-tahoma) has the issue?

2.14.0

### What version of Home Assistant Core has the issue?

2023.1.6

### Which gateway / hub do you use?

Cozytouch

### Device model

AtlanticElectricalHeaterWithAdjustableTemperatureSetpoint

### Home Assistant log

<details><summary>Logs</summary>

```
2023-01-20 20:15:21.844 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547209121168] Error handling message: Unknown error (unknown_error) from 176.145.91.18 (Mozilla/5.0 (Linux; Android 11; ONEPLUS A6003 Build/RKQ1.201217.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36 Home Assistant/2022.12.0-3026 (Android 11; ONEPLUS A6003))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 646, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1524, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 409, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 453, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 692, in _async_device_step
    await device_action.async_call_action_from_config(
  File "/usr/src/homeassistant/homeassistant/components/device_automation/action.py", line 76, in async_call_action_from_config
    await platform.async_call_action_from_config(hass, config, variables, context)
  File "/usr/src/homeassistant/homeassistant/components/number/device_action.py", line 62, in async_call_action_from_config
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 958, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 378, in async_set_value
    raise ValueError(
ValueError: Value 3.5 for Eco room temperature is outside valid range 6 - 29
```

</details>

**Comment by iMicknl** [comment]
Let's keep the discussion in core, we don't support ha-tahoma anymore, when your device is supported in core.
