### ISSUE TITLE
Not authenticated error.

### ISSUE THREAD

**Issue by vlebourl** [iMicknl/ha-tahoma#86]
**Describe the bug**
For some unknown reason, we get kicked out of the api, causing the following error message:
`{"errorCode":"RESOURCE_ACCESS_DENIED","error":"Not authenticated"}`

**To Reproduce**
Don't know yet...

**Comment by mariwing** [comment]
This happens a lot to me, sometimes already after a restart, sometimes after one or more day. This is the complete error message I get flooded (litterally 100 of these entries):

2020-07-01 21:05:09 ERROR (MainThread) [homeassistant.helpers.entity] Update for cover.markise_hoyre fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 272, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
    self.update  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tahoma/cover.py", line 92, in update
    self.controller.get_states([self.tahoma_device])
  File "/config/custom_components/tahoma/tahoma_api.py", line 513, in get_states
    result = self.send_request(requests.get, BASE_URL + path, headers=header)
  File "/config/custom_components/tahoma/tahoma_api.py", line 120, in send_request
    self.send_request(method, url, headers, data, timeout, retries - 1)
  File "/config/custom_components/tahoma/tahoma_api.py", line 120, in send_request
    self.send_request(method, url, headers, data, timeout, retries - 1)
  File "/config/custom_components/tahoma/tahoma_api.py", line 120, in send_request
    self.send_request(method, url, headers, data, timeout, retries - 1)
  File "/config/custom_components/tahoma/tahoma_api.py", line 117, in send_request
    + request.text
Exception: Maximum number of consecutive retries reached. Error is:
{"errorCode":"RESOURCE_ACCESS_DENIED","error":"Not authenticated"}

**Comment by vlebourl** [comment]
Thanks for the report. Unfortunately I haven't found a way to reproduce it consistently to debug it... Still looking!

**Comment by vlebourl** [comment]
Can you try branch `fix-86`? Download [this zip](https://github.com/iMicknl/ha-tahoma/archive/fix-86.zip) and replace the folder tahoma installed through HACS by the one in the zip, restart HA and let me know if it helps.

**Comment by vlebourl** [comment]
> Can you try branch `fix-86`? Download [this zip](https://github.com/iMicknl/ha-tahoma/archive/fix-86.zip) and replace the folder tahoma installed through HACS by the one in the zip, restart HA and let me know if it helps.

If you haven't done it yet, it should work now!

**Comment by vlebourl** [comment]
fixed in 1.5alpha2 by #95

**Comment by vlebourl** [comment]
We manage to get authenticated, but we still don't know why we loose authentication at some point...

**Comment by rabesocke** [comment]
Just moved from the discussion in issue #93 
>can you edit the file tahoma_api.py and add the following line 157, just before the if not self.login()
_LOGGER.debug("not authenticated: login again.")
Restart HA a try again with debug log setup for the component (see here)

I will test this later and give you feedback.

**Comment by rabesocke** [comment]
I get no log entry when I move the cover (even when I change it to warning or error).

**Comment by vlebourl** [comment]
The log is only supposed to warn if you're not authenticated... Do you still have the delay?

**Comment by rabesocke** [comment]
Yes, the delay is still there (not always, but most of the time)

**Comment by vlebourl** [comment]
I just found something, can you check whether this might change something?
In the Tahoma web interface, go to your account:
![image](https://user-images.githubusercontent.com/5701372/86373704-fa0b3e80-bc83-11ea-89ff-e35de859d2a8.png)

Select "My Somfy Account" at the bottom, and check whether you gave access to your box. I have no idea whether this is actually important or not, but we never know.

**Comment by vlebourl** [comment]
I've added another debug message in branch https://github.com/iMicknl/ha-tahoma/archive/not-authenticated-error.zip
can you try it? Don't forget to activate debug logging.

**Comment by rabesocke** [comment]
> I just found something, can you check whether this might change something?
> In the Tahoma web interface, go to your account:
> ![image](https://user-images.githubusercontent.com/5701372/86373704-fa0b3e80-bc83-11ea-89ff-e35de859d2a8.png)
> 
> Select "My Somfy Account" at the bottom, and check whether you gave access to your box. I have no idea whether this is actually important or not, but we never know.

No change with this configuration

**Comment by vlebourl** [comment]
damn it :(
I just found this in the hidden doc regarding actions sent to the api: "Per-session rate-limit : 50 calls per 24 HOURS period for all operations of the same category (exec)"
Maybe this is the issue? 
Not sure though cause I also got this in the tahoma web interface:
![image](https://user-images.githubusercontent.com/5701372/86376834-e19d2300-bc87-11ea-979b-2c65331a95d4.png)

**Comment by rabesocke** [comment]
> I've added another debug message in branch https://github.com/iMicknl/ha-tahoma/archive/not-authenticated-error.zip
> can you try it? Don't forget to activate debug logging.

Still no log entry and still the same situation.

**Comment by vlebourl** [comment]
I've modified the log. You should get debug messages even if you're still authenticated.
This will flood your logs, but might give us info... 
Don't hesitate to revert!

**Comment by rabesocke** [comment]
This is an example of the entries:
```
2020-07-02 17:37:42 DEBUG (SyncWorker_6) [custom_components.tahoma.tahoma_device] should_wait(WZ West) authenticated: True
2020-07-02 17:37:42 DEBUG (SyncWorker_6) [custom_components.tahoma.tahoma_api] sending request
2020-07-02 17:37:42 DEBUG (SyncWorker_6) [custom_components.tahoma.tahoma_api] request sent
2020-07-02 17:37:42 DEBUG (SyncWorker_6) [custom_components.tahoma.tahoma_api] request success
2020-07-02 17:37:42 DEBUG (SyncWorker_6) [custom_components.tahoma.tahoma_api] sending request
2020-07-02 17:37:42 DEBUG (SyncWorker_6) [custom_components.tahoma.tahoma_api] request sent
2020-07-02 17:37:42 DEBUG (SyncWorker_6) [custom_components.tahoma.tahoma_api] request success
2020-07-02 17:37:46 DEBUG (SyncWorker_3) [custom_components.tahoma.tahoma_device] should_wait(Kind (Süd) Süd) authenticated: True
2020-07-02 17:37:46 DEBUG (SyncWorker_3) [custom_components.tahoma.tahoma_api] sending request
2020-07-02 17:37:46 DEBUG (SyncWorker_3) [custom_components.tahoma.tahoma_api] request sent
2020-07-02 17:37:46 DEBUG (SyncWorker_3) [custom_components.tahoma.tahoma_api] request success
2020-07-02 17:37:46 DEBUG (SyncWorker_3) [custom_components.tahoma.tahoma_api] sending request
2020-07-02 17:37:46 DEBUG (SyncWorker_3) [custom_components.tahoma.tahoma_api] request sent
2020-07-02 17:37:46 DEBUG (SyncWorker_3) [custom_components.tahoma.tahoma_api] request success
2020-07-02 17:37:47 DEBUG (SyncWorker_15) [custom_components.tahoma.tahoma_device] should_wait(Büro West) authenticated: True
2020-07-02 17:37:47 DEBUG (SyncWorker_15) [custom_components.tahoma.tahoma_api] sending request
2020-07-02 17:37:47 DEBUG (SyncWorker_15) [custom_components.tahoma.tahoma_api] request sent
2020-07-02 17:37:47 DEBUG (SyncWorker_15) [custom_components.tahoma.tahoma_api] request success
2020-07-02 17:37:47 DEBUG (SyncWorker_15) [custom_components.tahoma.tahoma_api] sending request
2020-07-02 17:37:47 DEBUG (SyncWorker_15) [custom_components.tahoma.tahoma_api] request sent
2020-07-02 17:37:47 DEBUG (SyncWorker_15) [custom_components.tahoma.tahoma_api] request success
2020-07-02 17:37:48 DEBUG (SyncWorker_17) [custom_components.tahoma.tahoma_device] should_wait(Bad) authenticated: True
2020-07-02 17:37:48 DEBUG (SyncWorker_17) [custom_components.tahoma.tahoma_api] sending request
2020-07-02 17:37:48 DEBUG (SyncWorker_17) [custom_components.tahoma.tahoma_api] request sent
2020-07-02 17:37:48 DEBUG (SyncWorker_17) [custom_components.tahoma.tahoma_api] request success
2020-07-02 17:37:48 DEBUG (SyncWorker_17) [custom_components.tahoma.tahoma_api] sending request
2020-07-02 17:37:48 DEBUG (SyncWorker_17) [custom_components.tahoma.tahoma_api] request sent
2020-07-02 17:37:48 DEBUG (SyncWorker_17) [custom_components.tahoma.tahoma_api] request success
2020-07-02 17:37:48 DEBUG (SyncWorker_5) [custom_components.tahoma.tahoma_device] should_wait(WZ Süd-West A/M) authenticated: True
2020-07-02 17:37:48 DEBUG (SyncWorker_5) [custom_components.tahoma.tahoma_api] sending request
2020-07-02 17:37:49 DEBUG (SyncWorker_5) [custom_components.tahoma.tahoma_api] request sent
2020-07-02 17:37:49 DEBUG (SyncWorker_5) [custom_components.tahoma.tahoma_api] request success
2020-07-02 17:37:49 DEBUG (SyncWorker_5) [custom_components.tahoma.tahoma_api] sending request
2020-07-02 17:37:49 DEBUG (SyncWorker_5) [custom_components.tahoma.tahoma_api] request sent
2020-07-02 17:37:49 DEBUG (SyncWorker_5) [custom_components.tahoma.tahoma_api] request success
2020-07-02 17:37:49 DEBUG (SyncWorker_10) [custom_components.tahoma.tahoma_device] should_wait(WZ Süd) authenticated: True
2020-07-02 17:37:49 DEBUG (SyncWorker_10) [custom_components.tahoma.tahoma_api] sending request
```

**Comment by vlebourl** [comment]
These are scheduled update calls. I don't see any delay there. Can you do an action, look for apply_action in the log, and post messages around it?

**Comment by rabesocke** [comment]
Here is the `apply_action` snippet. The interesting thing is, that I click the button at 18:21:01 in the HA iOS App and in the log it says 18:21:09

```
2020-07-02 18:21:08 DEBUG (SyncWorker_8) [custom_components.tahoma.tahoma_device] should_wait(WZ West) authenticated: True
2020-07-02 18:21:08 DEBUG (SyncWorker_8) [custom_components.tahoma.tahoma_api] sending request
2020-07-02 18:21:08 DEBUG (SyncWorker_8) [custom_components.tahoma.tahoma_api] request sent
2020-07-02 18:21:08 DEBUG (SyncWorker_8) [custom_components.tahoma.tahoma_api] request success
2020-07-02 18:21:08 DEBUG (SyncWorker_8) [custom_components.tahoma.tahoma_api] sending request
2020-07-02 18:21:08 DEBUG (SyncWorker_8) [custom_components.tahoma.tahoma_api] request sent
2020-07-02 18:21:08 DEBUG (SyncWorker_8) [custom_components.tahoma.tahoma_api] request success
2020-07-02 18:21:09 DEBUG (SyncWorker_12) [custom_components.tahoma.tahoma_device] apply_action(WZ Süd-Ost) authenticated: True
2020-07-02 18:21:09 DEBUG (SyncWorker_12) [custom_components.tahoma.tahoma_api] sending request
2020-07-02 18:21:09 DEBUG (SyncWorker_12) [custom_components.tahoma.tahoma_api] request sent
2020-07-02 18:21:09 DEBUG (SyncWorker_12) [custom_components.tahoma.tahoma_api] request success
2020-07-02 18:21:09 DEBUG (SyncWorker_12) [custom_components.tahoma.tahoma_device] should_wait(WZ Süd-Ost) authenticated: True
2020-07-02 18:21:09 DEBUG (SyncWorker_12) [custom_components.tahoma.tahoma_api] sending request
2020-07-02 18:21:10 DEBUG (SyncWorker_12) [custom_components.tahoma.tahoma_api] request sent
2020-07-02 18:21:10 DEBUG (SyncWorker_12) [custom_components.tahoma.tahoma_api] request success
2020-07-02 18:21:12 DEBUG (SyncWorker_4) [custom_components.tahoma.tahoma_device] should_wait(Kind (Süd) Süd) authenticated: True
```

**Comment by rabesocke** [comment]
I test it again and it is reproducible: I clicked the button at 18:24:45 and the cover reacts 10 seconds later. And the same for the stop button - it reacts 10 seconds later after I clicked the button in the HA iOS app.

```
2020-07-02 18:24:52 DEBUG (SyncWorker_1) [custom_components.tahoma.tahoma_api] sending request
2020-07-02 18:24:52 DEBUG (SyncWorker_1) [custom_components.tahoma.tahoma_api] request sent
2020-07-02 18:24:52 DEBUG (SyncWorker_1) [custom_components.tahoma.tahoma_api] request success
2020-07-02 18:24:53 DEBUG (SyncWorker_9) [custom_components.tahoma.tahoma_device] apply_action(WZ Süd-Ost) authenticated: True
2020-07-02 18:24:53 DEBUG (SyncWorker_9) [custom_components.tahoma.tahoma_api] sending request
2020-07-02 18:24:53 DEBUG (SyncWorker_9) [custom_components.tahoma.tahoma_api] request sent
2020-07-02 18:24:53 DEBUG (SyncWorker_9) [custom_components.tahoma.tahoma_api] request success
2020-07-02 18:24:53 DEBUG (SyncWorker_12) [custom_components.tahoma.tahoma_device] should_wait(WZ Süd-Ost) authenticated: True
```

```
2020-07-02 18:25:08 DEBUG (SyncWorker_19) [custom_components.tahoma.tahoma_api] sending request
2020-07-02 18:25:08 DEBUG (SyncWorker_19) [custom_components.tahoma.tahoma_api] request sent
2020-07-02 18:25:08 DEBUG (SyncWorker_19) [custom_components.tahoma.tahoma_api] request success
2020-07-02 18:25:08 DEBUG (SyncWorker_5) [custom_components.tahoma.tahoma_device] apply_action(WZ Süd-Ost) authenticated: True
2020-07-02 18:25:08 DEBUG (SyncWorker_5) [custom_components.tahoma.tahoma_api] sending request
2020-07-02 18:25:09 DEBUG (SyncWorker_5) [custom_components.tahoma.tahoma_api] request sent
2020-07-02 18:25:09 DEBUG (SyncWorker_5) [custom_components.tahoma.tahoma_api] request success
2020-07-02 18:25:09 DEBUG (SyncWorker_11) [custom_components.tahoma.tahoma_device] should_wait(WZ Süd-Ost) authenticated: True
```

**Comment by vlebourl** [comment]
Interesting. Are those 8 seconds the typical delay you observe? What command are you using exactly? The apply_action message is sent from the integration, the request messages from the API. It means, once the apply_action is received, no delay is observed

**Comment by rabesocke** [comment]
Since the update to 1.5-alpha2 the delay is normally between 2 and 12 seconds. Most time the delay is 8 till 10 seconds.
Is there any schedule for applying actions?

I use the Button down, up and stop of the entity card:
![image](https://user-images.githubusercontent.com/4104867/86386846-99373280-bc92-11ea-9109-98a5910ab1bd.png)

**Comment by vlebourl** [comment]
I added yet other log messages to time when the actions are received by the cover entity.

**Comment by rabesocke** [comment]
The delay is before the action is received by the cover entity:

Move down clicked at 19:00:45
```
2020-07-02 19:00:52 DEBUG (SyncWorker_3) [custom_components.tahoma.cover] close_cover(WZ Süd-Ost)
2020-07-02 19:00:52 DEBUG (SyncWorker_3) [custom_components.tahoma.tahoma_device] apply_action(WZ Süd-Ost) authenticated: True
2020-07-02 19:00:52 DEBUG (SyncWorker_3) [custom_components.tahoma.tahoma_api] sending request
2020-07-02 19:00:53 DEBUG (SyncWorker_3) [custom_components.tahoma.tahoma_api] request sent
```

Stop clicked at 19:01:00
```
2020-07-02 19:01:08 DEBUG (SyncWorker_1) [custom_components.tahoma.cover] stop_cover(WZ Süd-Ost)
2020-07-02 19:01:08 DEBUG (SyncWorker_1) [custom_components.tahoma.tahoma_device] apply_action(WZ Süd-Ost) authenticated: True
2020-07-02 19:01:08 DEBUG (SyncWorker_1) [custom_components.tahoma.tahoma_api] sending request
2020-07-02 19:01:09 DEBUG (SyncWorker_1) [custom_components.tahoma.tahoma_api] request sent
2020-07-02 19:01:09 DEBUG (SyncWorker_1) [custom_components.tahoma.tahoma_api] request success
```

**Comment by vlebourl** [comment]
I'm afraid it's not on our side... This might be related to the frontend, but we can't control what happens before the close_cover our stop_cover log message.

**Comment by rabesocke** [comment]
Ok. It's hard to say what the source is. I updated HA to 0.112 and because of the login issue I had to update tahoma to 1.5-alpha2. Before that I used HA 0.111.4 and tahoma 1.3.

What I don't unterstand: the Zigbee lights are responding immediately without delay.

**Comment by mariwing** [comment]
> I just found this in the hidden doc regarding actions sent to the api: "Per-session rate-limit : 50 calls per 24 HOURS period for all operations of the same category (exec)"
> Maybe this is the issue?

This comment might be completly idiotic and I might be thinking completely wrong :-) But I have only RTS devices, so none of them report any state at any time. Reading the log (and this is the part where I might be wrong) it seems that the integration is pulling the api for status. This is bound to not give any usable result since there is no state to report. If it is possible to from the device class see that it is an RTS device (or maybe some other way to determine that the device don't report status) you could save on the API call quota by not issuing status update calls for this device groups.

**Comment by vlebourl** [comment]
It's a good idea to not pull on rts devices indeed. But we are thinking of rewriting the whole update process to make it an event based push update instead of a regular poll. This will be quite some work so not for tomorrow... Nevertheless, updates aren't exec calls, so it shouldn't impact the quotas

**Comment by vlebourl** [comment]
I'll close this issue for now.
